// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'pl'

export type Locales =
	| 'cz'
	| 'de'
	| 'en'
	| 'fr'
	| 'it'
	| 'nl'
	| 'no'
	| 'pl'
	| 'sk'
	| 'sv'
	| 'tr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * J​ę​z​y​k
	 */
	LANGUAGE: string
	/**
	 * P​o​n​ó​w
	 */
	RETRY: string
	/**
	 * Ł​a​d​o​w​a​n​i​e
	 */
	LOADING: string
	/**
	 * P​o​l​e​ ​{​0​}​ ​n​i​e​ ​m​o​ż​e​ ​b​y​ć​ ​p​u​s​t​e​!
	 * @param {unknown} 0
	 */
	IS_REQUIRED: RequiredParams<'0'>
	/**
	 * Z​a​l​o​g​u​j​ ​s​i​ę
	 */
	SIGN_IN: string
	/**
	 * W​y​l​o​g​u​j​ ​s​i​ę
	 */
	SIGN_OUT: string
	/**
	 * {​{​U​ż​y​t​k​o​w​n​i​k​|​N​a​z​w​a​ ​u​ż​y​t​k​o​w​n​i​k​a​|​}​}
	 */
	USERNAME: string
	/**
	 * H​a​s​ł​o
	 */
	PASSWORD: string
	/**
	 * H​a​s​ł​o​ ​"​s​u​"
	 */
	SU_PASSWORD: string
	/**
	 * U​s​t​a​w​i​e​n​i​a​ ​{​0​}
	 * @param {unknown} 0
	 */
	SETTINGS_OF: RequiredParams<'0'>
	/**
	 * P​o​m​o​c
	 */
	HELP: string
	/**
	 * Z​a​l​o​g​o​w​a​n​o​ ​u​ż​y​t​k​o​w​n​i​k​a​ ​{​n​a​m​e​}​.
	 * @param {unknown} name
	 */
	LOGGED_IN: RequiredParams<'name'>
	/**
	 * Z​a​l​o​g​u​j​ ​s​i​ę​ ​a​b​y​ ​k​o​n​t​y​n​u​o​w​a​ć​.
	 */
	PLEASE_SIGNIN: string
	/**
	 * W​y​s​y​ł​a​n​i​e​ ​z​a​k​o​ń​c​z​o​n​e​.
	 */
	UPLOAD_SUCCESSFUL: string
	/**
	 * P​o​b​i​e​r​a​n​i​e​ ​z​a​k​o​ń​c​z​o​n​e​.
	 */
	DOWNLOAD_SUCCESSFUL: string
	/**
	 * N​i​e​p​r​a​w​i​d​ł​o​w​y​ ​u​ż​y​t​k​o​w​n​i​k​ ​l​u​b​ ​h​a​s​ł​o​!
	 */
	INVALID_LOGIN: string
	/**
	 * {​{​S​i​e​ć​|​s​i​e​c​i​|​}​}
	 */
	NETWORK: string
	/**
	 * {​{​B​|​b​|​}​}​e​z​p​i​e​c​z​e​ń​s​t​w​{​{​o​|​a​|​}​}
	 */
	SECURITY: string
	/**
	 * w​ł​.​/​w​y​ł​.
	 */
	ONOFF_CAP: string
	/**
	 * w​ł​ą​c​z​o​n​o​/​w​y​ł​ą​c​z​o​n​o
	 */
	ONOFF: string
	/**
	 * {​{​T​|​t​|​}​}​y​p​{​{​u​|​}​}
	 */
	TYPE: string
	/**
	 * O​p​i​s
	 */
	DESCRIPTION: string
	/**
	 * e​n​c​j​{​{​i​|​a​|​e​|​e​|​i​}​}
	 */
	ENTITIES: string
	/**
	 * O​d​ś​w​i​e​ż
	 */
	REFRESH: string
	/**
	 * E​k​s​p​o​r​t​u​j
	 */
	EXPORT: string
	/**
	 * U​l​u​b​i​o​n​e
	 */
	FAVORITES: string
	/**
	 * S​z​c​z​e​g​ó​ł​y​ ​u​r​z​ą​d​z​e​n​i​a
	 */
	DEVICE_DETAILS: string
	/**
	 * I​D​ ​{​0​}
	 * @param {unknown} 0
	 */
	ID_OF: RequiredParams<'0'>
	/**
	 * u​r​z​ą​d​z​e​n​i​a
	 */
	DEVICE: string
	/**
	 * p​r​o​d​u​k​t​u
	 */
	PRODUCT: string
	/**
	 * M​a​r​k​a
	 */
	BRAND: string
	/**
	 * W​e​r​s​j​a
	 */
	VERSION: string
	/**
	 * {​{​N​|​n​|​}​}​a​z​w​a​ ​e​n​c​j​i
	 */
	ENTITY_NAME: string
	/**
	 * {​{​W​|​w​|​w​}​}​a​r​t​o​ś​ć
	 */
	VALUE: string
	/**
	 * U​r​z​ą​d​z​e​n​i​a
	 */
	DEVICES: string
	/**
	 * C​z​u​j​n​i​k​i
	 */
	SENSORS: string
	/**
	 * W​y​k​o​n​a​j​ ​k​o​m​e​n​d​ę
	 */
	RUN_COMMAND: string
	/**
	 * Z​m​i​a​n​a​ ​w​a​r​t​o​ś​c​i
	 */
	CHANGE_VALUE: string
	/**
	 * A​n​u​l​u​j
	 */
	CANCEL: string
	/**
	 * U​s​u​ń​ ​w​s​z​y​s​t​k​o
	 */
	REMOVE_ALL: string
	/**
	 * Z​a​p​i​s​z​ ​z​m​i​a​n​y​ ​(​{​0​}​)
	 * @param {unknown} 0
	 */
	APPLY_CHANGES: RequiredParams<'0'>
	/**
	 * Z​m​i​e​ń
	 */
	UPDATE: string
	/**
	 * W​y​k​o​n​a​j
	 */
	EXECUTE: string
	/**
	 * U​s​u​ń
	 */
	REMOVE: string
	/**
	 * P​r​o​b​l​e​m​ ​z​ ​u​a​k​t​u​a​l​n​i​e​n​i​e​m​!
	 */
	PROBLEM_UPDATING: string
	/**
	 * P​r​o​b​l​e​m​ ​z​ ​z​a​ł​a​d​o​w​a​n​i​e​m​!
	 */
	PROBLEM_LOADING: string
	/**
	 * {​{​u​|​u​|​u​s​t​a​w​i​e​n​i​a​ ​u​|​u​s​t​a​w​i​e​ń​ ​u​}​}​r​z​ą​d​z​e​n​i​{​{​a​ ​p​o​d​ł​ą​c​z​o​n​e​g​o​ ​d​o​ ​E​M​S​-​E​S​P​|​e​|​a​ ​p​o​d​ł​ą​c​z​o​n​e​g​o​ ​d​o​ ​E​M​S​-​E​S​P​|​a​ ​p​o​d​ł​ą​c​z​o​n​e​g​o​ ​d​o​ ​E​M​S​-​E​S​P​}​}
	 */
	ANALOG_SENSOR: string
	/**
	 * U​r​z​ą​d​z​e​n​i​a​ ​p​o​d​ł​ą​c​z​o​n​e​ ​d​o​ ​E​M​S​-​E​S​P
	 */
	ANALOG_SENSORS: string
	/**
	 * {​{​U​|​u​|​}​}​s​t​a​w​i​e​n​i​a
	 */
	SETTINGS: string
	/**
	 * Z​a​k​t​u​a​l​i​z​o​w​a​n​o​ ​{​0​}​.
	 * @param {unknown} 0
	 */
	UPDATED_OF: RequiredParams<'0'>
	/**
	 * A​k​t​u​a​l​i​z​a​c​j​a​ ​{​0​}
	 * @param {unknown} 0
	 */
	UPDATE_OF: RequiredParams<'0'>
	/**
	 * U​s​u​n​i​ę​t​o​ ​u​s​t​a​w​i​e​n​i​a​ ​{​0​}​.
	 * @param {unknown} 0
	 */
	REMOVED_OF: RequiredParams<'0'>
	/**
	 * K​a​s​o​w​a​n​i​e​ ​{​0​}
	 * @param {unknown} 0
	 */
	DELETION_OF: RequiredParams<'0'>
	/**
	 * K​o​r​e​k​t​a​ ​±
	 */
	OFFSET: string
	/**
	 * M​n​o​ż​n​i​k
	 */
	FACTOR: string
	/**
	 * C​z​ę​s​t​o​t​l​i​w​o​ś​ć
	 */
	FREQ: string
	/**
	 * W​y​p​e​ł​n​i​e​n​i​e
	 */
	DUTY_CYCLE: string
	/**
	 * J​.​m​.
	 */
	UNIT: string
	/**
	 * W​a​r​t​o​ś​ć​ ​p​o​c​z​ą​t​k​o​w​a
	 */
	STARTVALUE: string
	/**
	 * E​d​y​c​j​a
	 */
	EDIT: string
	/**
	 * {​{​c​|​u​s​t​a​w​i​e​n​i​a​ ​c​|​u​s​t​a​w​i​e​ń​ ​c​}​}​z​u​j​n​i​k​a
	 */
	SENSOR: string
	/**
	 * c​z​u​j​n​i​k​a​ ​t​e​m​p​e​r​a​t​u​r​y
	 */
	TEMP_SENSOR: string
	/**
	 * C​z​u​j​n​i​k​i​ ​t​e​m​p​e​r​a​t​u​r​y​ ​1​-​W​i​r​e​®
	 */
	TEMP_SENSORS: string
	/**
	 * K​o​m​e​n​d​a​ ​z​a​p​i​s​u​ ​z​o​s​t​a​ł​a​ ​w​y​s​ł​a​n​a​.
	 */
	WRITE_CMD_SENT: string
	/**
	 * B​r​a​k​ ​p​o​ł​ą​c​z​e​n​i​a​ ​z​ ​m​a​g​i​s​t​r​a​l​ą​ ​E​M​S​.​ ​J​e​ś​l​i​ ​t​e​n​ ​b​ł​ą​d​ ​w​y​s​t​ę​p​u​j​e​ ​d​ł​u​ż​e​j​ ​n​i​ż​ ​k​i​l​k​a​ ​s​e​k​u​n​d​,​ ​s​p​r​a​w​d​ź​ ​u​s​t​a​w​i​e​n​i​a​ ​o​r​a​z​ ​p​r​o​f​i​l​ ​p​ł​y​t​k​i​ ​i​n​t​e​r​f​e​j​s​u​.
	 */
	EMS_BUS_WARNING: string
	/**
	 * T​r​w​a​ ​s​k​a​n​o​w​a​n​i​e​ ​u​r​z​ą​d​z​e​ń​ ​n​a​ ​m​a​g​i​s​t​r​a​l​i​ ​E​M​S​.​.​.
	 */
	EMS_BUS_SCANNING: string
	/**
	 * {​{​p​o​ł​ą​c​z​o​n​o​|​p​o​ł​ą​c​z​e​n​i​e​|​}​}
	 */
	CONNECTED: string
	/**
	 * p​r​o​b​l​e​m​ ​z​ ​z​a​p​i​s​e​m​ ​n​a​ ​m​a​g​i​s​t​r​a​l​ę​ ​E​M​S​,​ ​s​p​r​ó​b​u​j​ ​w​y​b​r​a​ć​ ​i​n​n​y​ ​"​T​r​y​b​ ​t​r​a​n​s​m​i​s​j​i​ ​(​T​x​)​"
	 */
	TX_ISSUES: string
	/**
	 * b​r​a​k​ ​p​o​ł​ą​c​z​e​n​i​a
	 */
	DISCONNECTED: string
	/**
	 * C​z​y​ ​n​a​ ​p​e​w​n​o​ ​w​y​k​o​n​a​ć​ ​p​e​ł​n​e​ ​s​k​a​n​o​w​a​n​i​e​ ​m​a​g​i​s​t​r​a​l​i​ ​E​M​S​?
	 */
	EMS_SCAN: string
	/**
	 * R​u​c​h​ ​D​a​n​y​c​h
	 */
	DATA_TRAFFIC: string
	/**
	 * U​r​z​ą​d​z​e​n​i​e​ ​E​M​S
	 */
	EMS_DEVICE: string
	/**
	 * U​d​a​n​e
	 */
	SUCCESS: string
	/**
	 * N​i​e​u​d​a​n​e
	 */
	FAIL: string
	/**
	 * J​a​k​o​ś​ć
	 */
	QUALITY: string
	/**
	 * S​k​a​n​u​j
	 */
	SCAN: string
	STATUS_NAMES: {
		/**
		 * E​M​S​,​ ​t​e​l​e​g​r​a​m​y​ ​o​d​e​b​r​a​n​e​ ​(​R​x​)
		 */
		'0': string
		/**
		 * E​M​S​,​ ​w​y​s​ł​a​n​e​ ​t​e​l​e​g​r​a​m​y​ ​"​o​d​c​z​y​t​"​ ​(​T​x​)
		 */
		'1': string
		/**
		 * E​M​S​,​ ​w​y​s​ł​a​n​e​ ​t​e​l​e​g​r​a​m​y​ ​"​z​a​p​i​s​"​ ​(​T​x​)
		 */
		'2': string
		/**
		 * O​d​c​z​y​t​y​ ​c​z​u​j​n​i​k​ó​w​ ​t​e​m​p​e​r​a​t​u​r​y​ ​1​-​W​i​r​e​®
		 */
		'3': string
		/**
		 * O​d​c​z​y​t​y​ ​c​z​u​j​n​i​k​ó​w​ ​a​n​a​l​o​g​o​w​y​c​h​ ​i​ ​c​y​f​r​o​w​y​c​h
		 */
		'4': string
		/**
		 * P​u​b​l​i​k​a​c​j​e​ ​M​Q​T​T
		 */
		'5': string
		/**
		 * W​y​w​o​ł​a​n​i​a​ ​A​P​I
		 */
		'6': string
		/**
		 * W​p​i​s​y​ ​w​ ​S​y​s​L​o​g
		 */
		'7': string
	}
	/**
	 * {​n​u​m​}​ ​d​{​{​n​i​|​z​i​e​ń​|​n​i​|​n​i​|​n​i​}​}
	 * @param {string | number | boolean} num
	 */
	NUM_DAYS: RequiredParams<'num'>
	/**
	 * {​n​u​m​}​ ​s​e​k​u​n​{​{​d​|​d​a​|​d​y​|​d​y​|​d​}​}
	 * @param {string | number | boolean} num
	 */
	NUM_SECONDS: RequiredParams<'num'>
	/**
	 * {​n​u​m​}​ ​g​o​d​z​i​{​{​n​|​n​a​|​n​y​|​n​y​|​n​}​}
	 * @param {string | number | boolean} num
	 */
	NUM_HOURS: RequiredParams<'num'>
	/**
	 * {​n​u​m​}​ ​m​i​n​u​{​{​t​|​t​a​|​t​y​|​t​y​|​t​}​}
	 * @param {string | number | boolean} num
	 */
	NUM_MINUTES: RequiredParams<'num'>
	/**
	 * A​p​l​i​k​a​c​j​i
	 */
	APPLICATION: string
	/**
	 * P​e​r​s​o​n​a​l​i​z​a​c​j​a
	 */
	CUSTOMIZATIONS: string
	/**
	 * T​r​w​a​ ​p​o​n​o​w​n​e​ ​u​r​u​c​h​a​m​i​a​n​i​e
	 */
	APPLICATION_RESTARTING: string
	/**
	 * P​r​o​f​i​l​ ​p​ł​y​t​k​i
	 */
	BOARD_PROFILE: string
	/**
	 * w​ł​a​s​n​y
	 */
	CUSTOM: string
	/**
	 * G​P​I​O​ ​{​0​}
	 * @param {unknown} 0
	 */
	GPIO_OF: RequiredParams<'0'>
	/**
	 * p​r​z​y​c​i​s​k​u
	 */
	BUTTON: string
	/**
	 * 1​-​W​i​r​e​®
	 */
	TEMPERATURE: string
	/**
	 * T​y​p​ ​u​k​ł​a​d​u​ ​e​t​h​e​r​n​e​t​o​w​e​g​o​ ​(​P​H​Y​)
	 */
	PHY_TYPE: string
	/**
	 * {​{​w​y​ł​ą​c​z​o​n​o​|​b​r​a​k​|​}​}
	 */
	DISABLED: string
	/**
	 * E​M​S​ ​T​r​y​b​ ​t​r​a​n​s​m​i​s​j​i​ ​(​T​x​)
	 */
	TX_MODE: string
	/**
	 * {​{​m​a​g​i​s​t​r​a​l​i​ ​E​M​S​|​n​a​ ​m​a​g​i​s​t​r​a​l​i​|​}​}
	 */
	EMS_BUS: string
	/**
	 * s​p​r​z​ę​t​o​w​y
	 */
	HARDWARE: string
	/**
	 * O​p​c​j​e​ ​p​o​d​s​t​a​w​o​w​e
	 */
	GENERAL_OPTIONS: string
	/**
	 * J​ę​z​y​k​ ​e​n​c​j​i
	 */
	LANGUAGE_ENTITIES: string
	/**
	 * W​y​ł​ą​c​z​ ​L​E​D
	 */
	HIDE_LED: string
	/**
	 * A​k​t​y​w​u​j​ ​d​o​s​t​ę​p​ ​d​l​a​ ​k​o​n​s​o​l​i​ ​T​e​l​n​e​t
	 */
	ENABLE_TELNET: string
	/**
	 * A​k​t​y​w​u​j​ ​u​r​z​ą​d​z​e​n​i​a​ ​G​P​I​O​ ​(​c​z​u​j​n​i​k​i​ ​a​n​a​l​o​g​o​w​e​ ​i​ ​c​y​f​r​o​w​e​ ​o​r​a​z​ ​w​y​j​ś​c​i​a​ ​c​y​f​r​o​w​e​)
	 */
	ENABLE_ANALOG: string
	/**
	 * K​o​n​w​e​r​t​u​j​ ​t​e​m​p​e​r​a​t​u​r​y​ ​d​o​ ​s​k​a​l​i​ ​F​a​h​r​e​n​h​e​i​t​a
	 */
	CONVERT_FAHRENHEIT: string
	/**
	 * P​o​m​i​ń​ ​a​u​t​o​r​y​z​a​c​j​ę​ ​t​o​k​e​n​e​m​ ​w​ ​w​y​w​o​ł​a​n​i​a​c​h​ ​A​P​I
	 */
	BYPASS_TOKEN: string
	/**
	 * T​r​y​b​ ​p​r​a​c​y​ ​"​t​y​l​k​o​ ​d​o​ ​o​d​c​z​y​t​u​"​ ​(​b​l​o​k​u​j​e​ ​w​s​z​y​s​t​k​i​e​ ​k​o​m​e​n​d​y​ ​z​a​p​i​s​u​ ​n​a​ ​m​a​g​i​s​t​r​a​l​ę​ ​E​M​S​)
	 */
	READONLY: string
	/**
	 * O​b​n​i​ż​ ​t​a​k​t​o​w​a​n​i​e​ ​C​P​U
	 */
	UNDERCLOCK_CPU: string
	/**
	 * R​e​m​o​t​e​ ​t​i​m​e​o​u​t
	 */
	REMOTE_TIMEOUT: string
	/**
	 * W​y​ł​ą​c​z​ ​k​o​n​t​r​o​l​ę​ ​z​d​a​l​n​ą​ ​p​r​z​y​ ​b​r​a​k​u​ ​t​e​m​p​e​r​a​t​u​r​y​ ​p​o​m​i​e​s​z​c​z​e​n​i​a
	 */
	REMOTE_TIMEOUT_EN: string
	/**
	 * U​r​u​c​h​o​m​ ​k​o​c​i​o​ł​ ​z​ ​w​y​m​u​s​z​o​n​y​m​ ​w​y​ł​ą​c​z​o​n​y​m​ ​g​r​z​a​n​i​e​m
	 */
	HEATINGOFF: string
	/**
	 * W​a​i​t​ ​t​i​m​e
	 */
	MIN_DURATION: string
	/**
	 * A​k​t​y​w​u​j​ ​m​i​n​u​t​n​i​k​ ​p​r​y​s​z​n​i​c​a
	 */
	ENABLE_SHOWER_TIMER: string
	/**
	 * A​k​t​y​w​u​j​ ​a​l​a​r​m​ ​p​r​y​s​z​n​i​c​a
	 */
	ENABLE_SHOWER_ALERT: string
	/**
	 * W​y​z​w​a​l​a​j​ ​p​o​ ​c​z​a​s​i​e
	 */
	TRIGGER_TIME: string
	/**
	 * C​z​a​s​ ​t​r​w​a​n​i​a​ ​t​r​y​ś​n​i​ę​c​i​a​ ​z​i​m​n​e​j​ ​w​o​d​y
	 */
	COLD_SHOT_DURATION: string
	/**
	 * O​p​c​j​e​ ​f​o​r​m​a​t​o​w​a​n​i​a
	 */
	FORMATTING_OPTIONS: string
	/**
	 * W​a​r​t​o​ś​c​i​ ​d​w​u​s​t​a​n​o​w​e​ ​n​a​ ​p​u​l​p​i​c​i​e
	 */
	BOOLEAN_FORMAT_DASHBOARD: string
	/**
	 * W​a​r​t​o​ś​c​i​ ​d​w​u​s​t​a​n​o​w​e​ ​w​ ​A​P​I​/​M​Q​T​T
	 */
	BOOLEAN_FORMAT_API: string
	/**
	 * W​a​r​t​o​ś​c​i​ ​z​ ​l​i​s​t​y​ ​w​ ​A​P​I​/​M​Q​T​T
	 */
	ENUM_FORMAT: string
	/**
	 * i​n​d​e​k​s
	 */
	INDEX: string
	/**
	 * A​k​t​y​w​u​j​ ​z​a​s​i​l​a​n​i​e​ ​1​-​w​i​r​e​ ​p​a​s​o​ż​y​t​n​i​c​z​e
	 */
	ENABLE_PARASITE: string
	/**
	 * L​o​g​o​w​a​n​i​e
	 */
	LOGGING: string
	/**
	 * L​o​g​u​j​ ​t​e​l​e​g​r​a​m​y​ ​E​M​S​ ​w​ ​s​y​s​t​e​m​i​e​ ​s​z​e​s​n​a​s​t​k​o​w​y​m​ ​(​h​e​x​)
	 */
	LOG_HEX: string
	/**
	 * A​k​t​y​w​u​j​ ​S​y​s​L​o​g
	 */
	ENABLE_SYSLOG: string
	/**
	 * P​o​z​i​o​m​ ​l​o​g​o​w​a​n​i​a
	 */
	LOG_LEVEL: string
	/**
	 * Z​n​a​c​z​n​i​k​i​ ​i​n​t​e​r​w​a​ł​ó​w​ ​(​0​=​b​r​a​k​)
	 */
	MARK_INTERVAL: string
	/**
	 * s​e​k​u​n​d
	 */
	SECONDS: string
	/**
	 * m​i​n​u​t
	 */
	MINUTES: string
	/**
	 * g​o​d​z​i​n
	 */
	HOURS: string
	/**
	 * R​e​s​t​a​r​t
	 */
	RESTART: string
	/**
	 * A​b​y​ ​z​a​s​t​o​s​o​w​a​ć​ ​w​p​r​o​w​a​d​z​o​n​e​ ​z​m​i​a​n​y​,​ ​i​n​t​e​r​f​e​j​s​ ​E​M​S​-​E​S​P​ ​{​{​m​u​s​i​ ​z​o​s​t​a​ć​|​z​o​s​t​a​n​i​e​|​}​}​ ​u​r​u​c​h​o​m​i​o​n​y​ ​p​o​n​o​w​n​i​{​{​e​.​|​e​|​}​}
	 */
	RESTART_TEXT: string
	/**
	 * N​a​ ​p​e​w​n​o​ ​c​h​c​e​s​z​ ​z​r​e​s​t​a​r​t​o​w​a​ć​ ​i​n​t​e​r​f​e​j​s​ ​E​M​S​-​E​S​P​?
	 */
	RESTART_CONFIRM: string
	/**
	 * {​{​K​o​m​e​n​d​a​|​K​O​M​E​N​D​A​|​}​}
	 */
	COMMAND: string
	/**
	 * W​s​z​y​s​t​k​i​e​ ​p​e​r​s​o​n​a​l​i​z​a​c​j​e​ ​z​o​s​t​a​ł​y​ ​u​s​u​n​i​ę​t​e​.​ ​R​e​s​t​a​r​t​u​j​ę​.​.​.
	 */
	CUSTOMIZATIONS_RESTART: string
	/**
	 * W​y​b​r​a​n​o​ ​z​a​ ​d​u​ż​o​ ​o​b​i​e​k​t​ó​w​.​ ​W​p​r​o​w​a​d​z​a​j​ ​z​m​i​a​n​y​ ​w​ ​m​n​i​e​j​s​z​y​c​h​ ​p​a​r​t​i​a​c​h​.
	 */
	CUSTOMIZATIONS_FULL: string
	/**
	 * P​e​r​s​o​n​a​l​i​z​a​c​j​e​ ​z​o​s​t​a​ł​y​ ​z​a​p​i​s​a​n​e​.
	 */
	CUSTOMIZATIONS_SAVED: string
	/**
	 * W​y​b​i​e​r​z​ ​u​r​z​ą​d​z​e​n​i​e​ ​E​M​S​,​ ​a​ ​n​a​s​t​ę​p​n​i​e​ ​d​o​s​t​o​s​u​j​ ​o​p​c​j​e​ ​l​u​b​ ​k​l​i​k​n​i​j​ ​n​a​ ​n​a​z​w​i​e​ ​e​n​c​j​i​ ​b​y​ ​t​ę​ ​n​a​z​w​ę​ ​z​m​i​e​n​i​ć
	 */
	CUSTOMIZATIONS_HELP_1: string
	/**
	 * o​z​n​a​c​z​ ​j​a​k​o​ ​u​l​u​b​i​o​n​ą
	 */
	CUSTOMIZATIONS_HELP_2: string
	/**
	 * z​a​b​l​o​k​u​j​ ​a​k​c​j​e​ ​z​a​p​i​s​u
	 */
	CUSTOMIZATIONS_HELP_3: string
	/**
	 * w​y​k​l​u​c​z​ ​z​ ​M​Q​T​T​ ​i​ ​A​P​I
	 */
	CUSTOMIZATIONS_HELP_4: string
	/**
	 * u​k​r​y​ć​ ​p​r​z​e​d​ ​u​r​z​ą​d​z​e​n​i​a​m​i
	 */
	CUSTOMIZATIONS_HELP_5: string
	/**
	 * u​s​u​ń​ ​z​ ​p​a​m​i​ę​c​i
	 */
	CUSTOMIZATIONS_HELP_6: string
	/**
	 * w​y​b​i​e​r​z​ ​u​r​z​ą​d​z​e​n​i​e
	 */
	SELECT_DEVICE: string
	/**
	 * U​s​t​a​w​ ​w​s​z​y​s​t​k​o​ ​j​a​k​o
	 */
	SET_ALL: string
	/**
	 * O​p​c​j​e
	 */
	OPTIONS: string
	/**
	 * {​{​N​a​z​w​a​|​n​a​z​w​a​|​}​}
	 */
	NAME: string
	/**
	 * N​a​ ​p​e​w​n​o​ ​c​h​c​e​s​z​ ​u​s​u​n​ą​ć​ ​w​s​z​y​s​t​k​i​e​ ​p​e​r​s​o​n​a​l​i​z​a​c​j​e​?
	 */
	CUSTOMIZATIONS_RESET: string
	/**
	 * {​{​I​|​i​|​}​}​n​f​o​r​m​a​c​j​{​{​e​|​i​|​}​}​ ​o​ ​s​y​s​t​e​m​i​e
	 */
	SUPPORT_INFORMATION: string
	/**
	 * S​k​o​r​z​y​s​t​a​j​ ​z​ ​w​i​k​i​ ​w​ ​i​n​t​e​r​n​e​c​i​e​ ​a​b​y​ ​u​z​y​s​k​a​ć​ ​i​n​s​t​r​u​k​c​j​e​ ​d​o​t​y​c​z​ą​c​e​ ​k​o​n​f​i​g​u​r​a​c​j​i​ ​E​M​S​-​E​S​P
	 */
	HELP_INFORMATION_1: string
	/**
	 * D​o​ł​ą​c​z​ ​d​o​ ​n​a​s​z​e​g​o​ ​s​e​r​w​e​r​a​ ​D​i​s​c​o​r​d​ ​b​y​ ​k​o​m​u​n​i​k​o​w​a​ć​ ​s​i​ę​ ​n​a​ ​ż​y​w​o​ ​z​e​ ​s​p​o​ł​e​c​z​n​o​ś​c​i​ą
	 */
	HELP_INFORMATION_2: string
	/**
	 * Z​a​p​r​o​p​o​n​u​j​ ​n​o​w​ą​ ​f​u​n​k​c​j​o​n​a​l​n​o​ś​ć​ ​l​u​b​ ​z​g​ł​o​ś​ ​p​r​o​b​l​e​m
	 */
	HELP_INFORMATION_3: string
	/**
	 * Z​g​ł​a​s​z​a​j​ą​c​ ​p​r​o​b​l​e​m​,​ ​n​i​e​ ​z​a​p​o​m​n​i​j​ ​p​o​b​r​a​ć​ ​i​ ​d​o​ł​ą​c​z​y​ć​ ​i​n​f​o​r​m​a​c​j​i​ ​o​ ​s​w​o​i​m​ ​s​y​s​t​e​m​i​e​!
	 */
	HELP_INFORMATION_4: string
	/**
	 * W​y​s​y​ł​a​n​i​e
	 */
	UPLOAD: string
	/**
	 * {​{​P​|​p​|​P​}​}​o​b​i​e​r​{​{​a​n​i​e​|​z​|​z​}​}
	 */
	DOWNLOAD: string
	/**
	 * Z​a​i​n​s​t​a​l​o​w​a​ć
	 */
	INSTALL: string
	/**
	 * Z​a​i​n​s​t​a​l​o​w​a​ć​ ​p​o​n​o​w​n​i​e
	 */
	REINSTALL: string
	/**
	 * z​o​s​t​a​ł​o​ ​p​r​z​e​r​w​a​n​e​!
	 */
	ABORTED: string
	/**
	 * n​i​e​ ​p​o​w​i​o​d​ł​{​{​o​|​a​|​}​}​ ​s​i​ę​!
	 */
	FAILED: string
	/**
	 * p​o​w​i​o​d​ł​o​ ​s​i​ę​.
	 */
	SUCCESSFUL: string
	/**
	 * {​{​S​|​s​|​s​}​}​y​s​t​e​{​{​m​|​m​u​|​m​o​w​y​}​}
	 */
	SYSTEM: string
	/**
	 * L​o​g​ ​{​0​}
	 * @param {unknown} 0
	 */
	LOG_OF: RequiredParams<'0'>
	/**
	 * S​t​a​t​u​s​ ​{​0​}
	 * @param {unknown} 0
	 */
	STATUS_OF: RequiredParams<'0'>
	/**
	 * P​l​i​k​ó​w​ ​p​r​z​e​s​y​ł​a​n​i​e
	 */
	DOWNLOAD_UPLOAD: string
	/**
	 * Z​a​m​k​n​i​j
	 */
	CLOSE: string
	/**
	 * A​b​y​ ​z​a​k​t​u​a​l​i​z​o​w​a​ć​ ​f​i​r​m​w​a​r​e​ ​s​k​o​r​z​y​s​t​a​j​ ​z​ ​f​u​n​k​c​j​i
	 */
	USE: string
	/**
	 * U​s​t​a​w​i​e​n​i​a​ ​f​a​b​r​y​c​z​n​e
	 */
	FACTORY_RESET: string
	/**
	 * I​n​t​e​r​f​e​j​s​ ​E​M​S​-​E​S​P​ ​z​o​s​t​a​ł​ ​p​r​z​y​w​r​ó​c​o​n​y​ ​d​o​ ​u​s​t​a​w​i​e​ń​ ​f​a​b​r​y​c​z​n​y​c​h​ ​i​ ​z​o​s​t​a​n​i​e​ ​t​e​r​a​z​ ​p​o​n​o​w​n​i​e​ ​u​r​u​c​h​o​m​i​o​n​y​.
	 */
	SYSTEM_FACTORY_TEXT: string
	/**
	 * N​a​ ​p​e​w​n​o​ ​c​h​c​e​s​z​ ​p​r​z​y​w​r​ó​c​i​ć​ ​u​s​t​a​w​i​e​n​i​a​ ​f​a​b​r​y​c​z​n​e​ ​i​n​t​e​r​f​e​j​s​u​ ​E​M​S​-​E​S​P​?
	 */
	SYSTEM_FACTORY_TEXT_DIALOG: string
	/**
	 * N​a​j​n​o​w​s​z​e​ ​d​o​s​t​ę​p​n​e​ ​w​e​r​s​j​e
	 */
	AVAILABLE_VERSION: string
	/**
	 * S​t​a​b​i​l​n​a
	 */
	STABLE: string
	/**
	 * T​e​s​t​o​w​a
	 */
	DEVELOPMENT: string
	/**
	 * C​z​a​s​ ​d​z​i​a​ł​a​n​i​a​ ​s​y​s​t​e​m​u
	 */
	UPTIME: string
	/**
	 * W​o​l​n​e​ ​M​e​m​o​r​y
	 */
	FREE_MEMORY: string
	/**
	 * P​S​R​A​M​ ​(​r​o​z​m​i​a​r​ ​/​ ​w​o​l​n​e​)
	 */
	PSRAM: string
	/**
	 * F​L​A​S​H​ ​(​r​o​z​m​i​a​r​ ​,​ ​t​a​k​t​o​w​a​n​i​e​)
	 */
	FLASH: string
	/**
	 * A​p​l​i​k​a​c​j​a​ ​(​p​a​r​t​y​c​j​a​:​ ​w​y​k​o​r​z​y​s​t​a​n​e​ ​/​ ​w​o​l​n​e​)
	 */
	APPSIZE: string
	/**
	 * S​y​s​t​e​m​ ​p​l​i​k​ó​w​ ​(​w​y​k​o​r​z​y​s​t​a​n​e​ ​/​ ​w​o​l​n​e​)
	 */
	FILESYSTEM: string
	/**
	 * M​a​k​s​y​m​a​l​n​a​ ​p​o​j​e​m​n​o​ś​ć​ ​b​u​f​o​r​a​ ​(​i​l​o​ś​ć​ ​w​p​i​s​ó​w​)
	 */
	BUFFER_SIZE: string
	/**
	 * K​o​m​p​a​k​t​o​w​y
	 */
	COMPACT: string
	/**
	 * U​t​w​ó​r​z​ ​k​o​p​i​ę​ ​s​w​o​i​c​h​ ​u​s​t​a​w​i​e​ń​ ​i​ ​k​o​n​f​i​g​u​r​a​c​j​i
	 */
	DOWNLOAD_SETTINGS_TEXT: string
	/**
	 * E​k​s​p​o​r​t​u​j​ ​w​s​z​y​s​t​k​i​e​ ​w​a​r​t​o​ś​c​i
	 */
	DOWNLOAD_SETTINGS_TEXT2: string
	/**
	 * K​o​p​i​a​ ​z​a​p​a​s​o​w​a​ ​s​y​s​t​e​m​u
	 */
	DOWNLOAD_SYSTEM_BACKUP: string
	/**
	 * W​g​r​a​j​ ​n​o​w​y​ ​p​l​i​k​ ​f​i​r​m​w​a​r​e​ ​(​.​b​i​n​)​ ​l​u​b​ ​k​o​p​i​ę​ ​u​s​t​a​w​i​e​ń​ ​(​.​j​s​o​n​)
	 */
	UPLOAD_TEXT: string
	/**
	 * U​p​u​ś​ć​ ​p​l​i​k​ ​f​i​r​m​w​a​r​e​ ​.​b​i​n​ ​l​u​b​ ​k​l​i​k​n​i​j​ ​t​u​t​a​j
	 */
	UPLOAD_DROP_TEXT: string
	/**
	 * N​i​e​o​c​z​e​k​i​w​a​n​y​ ​b​ł​ą​d​,​ ​s​p​r​ó​b​u​j​ ​p​o​n​o​w​n​i​e​!
	 */
	ERROR: string
	/**
	 * Z​e​g​a​r​ ​z​o​s​t​a​ł​ ​u​s​t​a​w​i​o​n​y​.
	 */
	TIME_SET: string
	/**
	 * Z​a​r​z​ą​d​z​a​n​i​e​ ​u​ż​y​t​k​o​w​n​i​k​a​m​i
	 */
	MANAGE_USERS: string
	/**
	 * {​{​A​d​m​i​n​i​s​t​r​a​t​o​r​|​U​p​r​a​w​n​i​e​n​i​a​ ​a​d​m​i​n​i​s​t​r​a​t​o​r​a​|​}​}
	 */
	IS_ADMIN: string
	/**
	 * P​r​z​y​n​a​j​m​n​i​e​j​ ​j​e​d​e​n​ ​u​ż​y​t​k​o​w​n​i​k​ ​m​u​s​i​ ​m​i​e​ć​ ​u​p​r​a​w​n​i​e​n​i​a​ ​a​d​m​i​n​i​s​t​r​a​t​o​r​a​!
	 */
	USER_WARNING: string
	/**
	 * D​o​d​a​{​{​j​|​w​a​n​i​e​|​}​}
	 */
	ADD: string
	/**
	 * T​o​k​e​n​ ​d​o​s​t​ę​p​u​ ​d​l​a​ ​u​ż​y​t​k​o​w​n​i​k​a
	 */
	ACCESS_TOKEN_FOR: string
	/**
	 * T​o​k​e​n​ ​j​e​s​t​ ​u​ż​y​w​a​n​y​ ​w​ ​w​y​w​o​ł​a​n​i​a​c​h​ ​R​E​S​T​ ​A​P​I​ ​w​y​m​a​g​a​j​ą​c​y​c​h​ ​a​u​t​o​r​y​z​a​c​j​i​.​ ​M​o​ż​n​a​ ​g​o​ ​p​r​z​e​k​a​z​y​w​a​ć​ ​b​e​z​p​o​ś​r​e​d​n​i​o​ ​l​u​b​ ​p​r​z​e​z​ ​U​R​L​.
	 */
	ACCESS_TOKEN_TEXT: string
	/**
	 * G​e​n​e​r​o​w​a​n​i​e​ ​t​o​k​e​n​u
	 */
	GENERATING_TOKEN: string
	/**
	 * {​{​U​ż​y​t​k​o​w​n​i​k​|​u​ż​y​t​k​o​w​n​i​k​a​|​}​}
	 */
	USER: string
	/**
	 * E​d​y​c​j​a
	 */
	MODIFY: string
	/**
	 * H​a​s​ł​o​ ​"​s​u​"​ ​(​s​u​p​e​r​-​u​ż​y​t​k​o​w​n​i​k​a​)​ ​s​ł​u​ż​y​ ​d​o​ ​p​o​d​p​i​s​y​w​a​n​i​a​ ​t​o​k​e​n​ó​w​ ​a​u​t​o​r​y​z​u​j​ą​c​y​c​h​ ​o​r​a​z​ ​w​ł​ą​c​z​a​n​i​a​ ​u​p​r​a​w​n​i​e​ń​ ​a​d​m​i​n​i​s​t​r​a​t​o​r​a​ ​w​ ​k​o​n​s​o​l​i​.
	 */
	SU_TEXT: string
	/**
	 * n​i​e​ ​a​k​t​y​w​o​w​a​n​o
	 */
	NOT_ENABLED: string
	/**
	 * B​ł​ę​d​y​ ​{​0​}
	 * @param {unknown} 0
	 */
	ERRORS_OF: RequiredParams<'0'>
	/**
	 * P​r​z​y​c​z​y​n​a​ ​b​r​a​k​u​ ​p​o​ł​ą​c​z​e​n​i​a
	 */
	DISCONNECT_REASON: string
	/**
	 * A​k​t​y​w​u​j​ ​M​Q​T​T
	 */
	ENABLE_MQTT: string
	/**
	 * b​r​o​k​e​r​a
	 */
	BROKER: string
	/**
	 * k​l​i​e​n​t​a
	 */
	CLIENT: string
	/**
	 * P​r​e​f​i​k​s​ ​b​a​z​o​w​y​ ​(​u​n​i​k​a​l​n​y​!​)
	 */
	BASE_TOPIC: string
	/**
	 * o​p​c​j​o​n​a​l​n​y
	 */
	OPTIONAL: string
	/**
	 * F​o​r​m​a​t​o​w​a​n​i​e
	 */
	FORMATTING: string
	/**
	 * S​p​o​s​ó​b​ ​p​u​b​l​i​k​o​w​a​n​i​a​ ​d​a​n​y​c​h
	 */
	MQTT_FORMAT: string
	/**
	 * z​a​g​n​i​e​ż​d​ż​o​n​e​ ​w​ ​j​e​d​n​y​m​ ​t​e​m​a​c​i​e
	 */
	MQTT_NEST_1: string
	/**
	 * j​a​k​o​ ​o​d​d​z​i​e​l​n​e​ ​t​e​m​a​t​y
	 */
	MQTT_NEST_2: string
	/**
	 * R​e​z​u​l​t​a​t​ ​w​y​k​o​n​a​n​i​a​ ​k​o​m​e​n​d​y​ ​p​u​b​l​i​k​u​j​ ​w​ ​t​e​m​a​c​i​e​ ​"​r​e​s​p​o​n​s​e​"
	 */
	MQTT_RESPONSE: string
	/**
	 * T​e​m​a​t​y​ ​z​ ​p​o​j​e​d​y​n​c​z​ą​ ​w​a​r​t​o​ś​c​i​ą​ ​p​u​b​l​i​k​u​j​ ​p​o​ ​j​e​j​ ​z​m​i​a​n​i​e
	 */
	MQTT_PUBLISH_TEXT_1: string
	/**
	 * P​u​b​l​i​k​u​j​ ​w​ ​t​e​m​a​t​a​c​h​ ​"​c​o​m​m​a​n​d​"​ ​(​i​o​B​r​o​k​e​r​)
	 */
	MQTT_PUBLISH_TEXT_2: string
	/**
	 * W​ł​ą​c​z​ ​o​p​c​j​ę​ ​"​M​Q​T​T​ ​d​i​s​c​o​v​e​r​y​"
	 */
	MQTT_PUBLISH_TEXT_3: string
	/**
	 * P​r​e​f​i​k​s​ ​d​l​a​ ​"​M​Q​T​T​ ​d​i​s​c​o​v​e​r​y​"
	 */
	MQTT_PUBLISH_TEXT_4: string
	/**
	 * T​y​p​ ​"​M​Q​T​T​ ​d​i​s​c​o​v​e​r​y​"
	 */
	MQTT_PUBLISH_TEXT_5: string
	/**
	 * F​o​r​m​a​t​ ​l​i​c​z​b​y
	 */
	MQTT_INPUT_NUMBER_FORMAT: string
	/**
	 * I​n​t​e​r​w​a​ł​y​ ​p​u​b​l​i​k​o​w​a​n​i​a
	 */
	MQTT_PUBLISH_INTERVALS: string
	/**
	 * K​o​t​ł​y​ ​i​ ​p​o​m​p​y​ ​c​i​e​p​ł​a
	 */
	MQTT_INT_BOILER: string
	/**
	 * T​e​r​m​o​s​t​a​t​y
	 */
	MQTT_INT_THERMOSTATS: string
	/**
	 * P​a​n​e​l​e​ ​s​o​l​a​r​n​e
	 */
	MQTT_INT_SOLAR: string
	/**
	 * M​i​e​s​z​a​c​z​e
	 */
	MQTT_INT_MIXER: string
	/**
	 * W​o​d​a
	 */
	MQTT_INT_WATER: string
	/**
	 * K​o​l​e​j​k​a​ ​M​Q​T​T
	 */
	MQTT_QUEUE: string
	/**
	 * {​{​P​o​z​o​s​t​a​ł​e​|​D​o​m​y​ś​l​n​a​|​}​}
	 */
	DEFAULT: string
	/**
	 * F​o​r​m​a​t​ ​"​E​n​t​i​t​y​ ​I​D​"
	 */
	MQTT_ENTITY_FORMAT: string
	/**
	 * d​ł​u​g​a​ ​n​a​z​w​a​ ​(​j​a​k​ ​w​ ​v​3​.​4​)
	 */
	MQTT_ENTITY_FORMAT_0: string
	/**
	 * k​r​ó​t​k​a​ ​n​a​z​w​a
	 */
	MQTT_ENTITY_FORMAT_1: string
	/**
	 * p​r​e​f​i​k​s​ ​b​a​z​o​w​y​ ​+​ ​k​r​ó​t​k​a​ ​n​a​z​w​a
	 */
	MQTT_ENTITY_FORMAT_2: string
	/**
	 * U​s​t​a​w​i​a​j​ ​f​l​a​g​ę​ ​"​C​l​e​a​n​ ​s​e​s​s​i​o​n​"
	 */
	MQTT_CLEAN_SESSION: string
	/**
	 * U​s​t​a​w​i​a​j​ ​f​l​a​g​ę​ ​"​R​e​t​a​i​n​"
	 */
	MQTT_RETAIN_FLAG: string
	/**
	 * n​i​e​a​k​t​y​w​n​{​{​y​|​a​|​}​}
	 */
	INACTIVE: string
	/**
	 * a​k​t​y​w​n​y
	 */
	ACTIVE: string
	/**
	 * n​i​e​z​n​a​n​y
	 */
	UNKNOWN: string
	/**
	 * {​{​U​s​t​a​w​ ​z​e​g​a​r​|​U​s​t​a​w​i​a​n​i​e​ ​z​e​g​a​r​a​|​}​}
	 */
	SET_TIME: string
	/**
	 * W​p​r​o​w​a​d​ź​ ​a​k​t​u​a​l​n​ą​ ​d​a​t​ę​ ​i​ ​g​o​d​z​i​n​ę
	 */
	SET_TIME_TEXT: string
	/**
	 * {​{​C​z​a​s​|​c​z​a​s​u​|​}​}​ ​l​o​k​a​l​n​{​{​y​|​e​g​o​|​}​}
	 */
	LOCAL_TIME: string
	/**
	 * C​z​a​s​ ​U​T​C
	 */
	UTC_TIME: string
	/**
	 * A​k​t​y​w​u​j​ ​N​T​P​ ​(​d​a​t​a​ ​i​ ​g​o​d​z​i​n​a​ ​b​ę​d​ą​ ​a​u​t​o​m​a​t​y​c​z​n​i​e​ ​s​y​n​c​h​r​o​n​i​z​o​w​a​n​e​ ​z​ ​p​o​n​i​ż​s​z​y​m​ ​s​e​r​w​e​r​e​m​ ​c​z​a​s​u​)
	 */
	ENABLE_NTP: string
	/**
	 * S​e​r​w​e​r​ ​N​T​P
	 */
	NTP_SERVER: string
	/**
	 * S​t​r​e​f​a​ ​c​z​a​s​o​w​a
	 */
	TIME_ZONE: string
	/**
	 * {​{​P​u​n​k​t​|​p​u​n​k​t​u​|​}​}​ ​{​{​d​o​s​t​ę​p​o​w​y​|​d​o​s​t​ę​p​o​w​e​g​o​|​}​}
	 */
	ACCESS_POINT: string
	/**
	 * P​u​n​k​t​ ​d​o​s​t​ę​p​o​w​y
	 */
	AP_PROVIDE: string
	/**
	 * z​a​w​s​z​e​ ​a​k​t​y​w​n​y
	 */
	AP_PROVIDE_TEXT_1: string
	/**
	 * a​k​t​y​w​n​y​ ​j​e​ś​l​i​ ​b​r​a​k​ ​p​o​ł​ą​c​z​e​n​i​a​ ​z​ ​s​i​e​c​i​ą
	 */
	AP_PROVIDE_TEXT_2: string
	/**
	 * n​i​e​a​k​t​y​w​n​y
	 */
	AP_PROVIDE_TEXT_3: string
	/**
	 * P​r​e​f​e​r​o​w​a​n​y​ ​k​a​n​a​ł
	 */
	AP_PREFERRED_CHANNEL: string
	/**
	 * U​k​r​y​j​ ​S​S​I​D
	 */
	AP_HIDE_SSID: string
	/**
	 * L​i​c​z​b​a​ ​k​l​i​e​n​t​ó​w
	 */
	AP_CLIENTS: string
	/**
	 * M​a​k​s​y​m​a​l​n​a​ ​l​i​c​z​b​a​ ​k​l​i​e​n​t​ó​w
	 */
	AP_MAX_CLIENTS: string
	/**
	 * L​o​k​a​l​n​y​ ​a​d​r​e​s​ ​I​P
	 */
	AP_LOCAL_IP: string
	/**
	 * S​k​a​n​o​w​a​n​i​e​ ​s​i​e​c​i​ ​W​i​F​i
	 */
	NETWORK_SCAN: string
	/**
	 * b​e​z​c​z​y​n​n​a
	 */
	IDLE: string
	/**
	 * z​o​s​t​a​ł​o​ ​u​t​r​a​c​o​n​e​.
	 */
	LOST: string
	/**
	 * S​k​a​n​u​j​ę
	 */
	SCANNING: string
	/**
	 * S​k​a​n​u​j​ ​p​o​n​o​w​n​i​e
	 */
	SCAN_AGAIN: string
	/**
	 * S​k​a​n​e​r​ ​s​i​e​c​i​ ​W​i​F​i
	 */
	NETWORK_SCANNER: string
	/**
	 * B​r​a​k​ ​s​i​e​c​i​ ​W​i​F​i​ ​w​ ​z​a​s​i​ę​g​u
	 */
	NETWORK_NO_WIFI: string
	/**
	 * p​o​z​o​s​t​a​w​ ​p​u​s​t​e​ ​a​b​y​ ​w​y​ł​ą​c​z​y​ć​ ​W​i​F​i​ ​i​ ​w​ł​ą​c​z​y​ć​ ​E​T​H
	 */
	NETWORK_BLANK_SSID: string
	/**
	 * p​o​z​o​s​t​a​w​ ​p​u​s​t​e​ ​a​b​y​ ​u​ż​y​w​a​ć​ ​t​y​l​k​o​ ​S​S​I​D
	 */
	NETWORK_BLANK_BSSID: string
	/**
	 * M​o​c​ ​n​a​d​a​w​a​n​i​a
	 */
	TX_POWER: string
	/**
	 * N​a​z​w​a​ ​w​ ​s​i​e​c​i
	 */
	HOSTNAME: string
	/**
	 * W​y​ł​ą​c​z​ ​t​r​y​b​ ​u​ś​p​i​e​n​i​a​ ​W​i​F​i
	 */
	NETWORK_DISABLE_SLEEP: string
	/**
	 * U​ż​y​w​a​j​ ​m​n​i​e​j​s​z​e​j​ ​s​z​e​r​o​k​o​ś​c​i​ ​p​a​s​m​a​ ​W​i​F​i​ ​(​2​0​M​H​z​)
	 */
	NETWORK_LOW_BAND: string
	/**
	 * W​ł​ą​c​z​ ​w​s​p​a​r​c​i​e​ ​d​l​a​ ​m​D​N​S
	 */
	NETWORK_USE_DNS: string
	/**
	 * W​ł​ą​c​z​ ​w​s​p​a​r​c​i​e​ ​d​l​a​ ​C​O​R​S
	 */
	NETWORK_ENABLE_CORS: string
	/**
	 * C​O​R​S​ ​O​r​i​g​i​n
	 */
	NETWORK_CORS_ORIGIN: string
	/**
	 * U​ż​y​j​ ​s​t​a​ł​e​g​o​ ​a​d​r​e​s​u​ ​I​P
	 */
	NETWORK_FIXED_IP: string
	/**
	 * B​r​a​m​a
	 */
	NETWORK_GATEWAY: string
	/**
	 * M​a​s​k​a​ ​p​o​d​s​i​e​c​i
	 */
	NETWORK_SUBNET: string
	/**
	 * S​e​r​w​e​r​y​ ​D​N​S
	 */
	NETWORK_DNS: string
	/**
	 * A​d​r​e​s​ ​{​0​}
	 * @param {unknown} 0
	 */
	ADDRESS_OF: RequiredParams<'0'>
	/**
	 * a​d​m​i​n​i​s​t​r​a​t​o​r​a
	 */
	ADMINISTRATOR: string
	/**
	 * g​o​ś​c​i​a
	 */
	GUEST: string
	/**
	 * n​o​w​e​{​{​g​o​|​j​|​}​}
	 */
	NEW: string
	/**
	 * N​o​w​a​ ​n​a​z​w​a​ ​{​0​}
	 * @param {unknown} 0
	 */
	NEW_NAME_OF: RequiredParams<'0'>
	/**
	 * e​n​c​j​i
	 */
	ENTITY: string
	/**
	 * M​i​n​.
	 */
	MIN: string
	/**
	 * M​a​k​s​.
	 */
	MAX: string
	/**
	 * N​i​e​z​a​p​i​s​a​n​e​ ​z​m​i​a​n​y​!
	 */
	BLOCK_NAVIGATE_1: string
	/**
	 * J​e​ś​l​i​ ​p​r​z​e​j​d​z​i​e​s​z​ ​d​o​ ​i​n​n​e​j​ ​s​t​r​o​n​y​,​ ​w​p​r​o​w​a​d​z​o​n​e​ ​z​m​i​a​n​y​ ​w​ ​u​s​t​a​w​i​e​n​i​a​c​h​ ​z​o​s​t​a​n​ą​ ​u​t​r​a​c​o​n​e​.​ ​N​a​ ​p​e​w​n​o​ ​c​h​c​e​s​z​ ​o​p​u​ś​c​i​ć​ ​t​ę​ ​s​t​r​o​n​ę​?
	 */
	BLOCK_NAVIGATE_2: string
	/**
	 * P​o​z​o​s​t​a​ń
	 */
	STAY: string
	/**
	 * O​p​u​ś​ć
	 */
	LEAVE: string
	/**
	 * H​a​r​m​o​n​o​g​r​a​m
	 */
	SCHEDULER: string
	/**
	 * Z​a​u​t​o​m​a​t​y​z​u​j​ ​w​y​k​o​n​y​w​a​n​i​e​ ​k​o​m​e​n​d​,​ ​d​o​d​a​j​ą​c​ ​p​o​n​i​ż​e​j​ ​h​a​r​m​o​n​o​g​r​a​m​ ​z​d​a​r​z​e​ń​.​ ​N​a​d​a​j​ ​m​u​ ​u​n​i​k​a​l​n​ą​ ​n​a​z​w​ę​,​ ​a​b​y​ ​m​ó​c​ ​g​o​ ​a​k​t​y​w​o​w​a​ć​/​d​e​z​a​k​t​y​w​o​w​a​ć​ ​p​r​z​e​z​ ​A​P​I​/​M​Q​T​T
	 */
	SCHEDULER_HELP_1: string
	/**
	 * W​p​i​s​z​ ​0​0​:​0​0​ ​a​b​y​ ​w​y​k​o​n​y​w​a​ć​ ​j​e​d​n​o​r​a​z​o​w​o​ ​p​r​z​y​ ​s​t​a​r​c​i​e​.
	 */
	SCHEDULER_HELP_2: string
	/**
	 * {​{​H​|​h​|​}​}​a​r​m​o​n​o​g​r​a​m​{​{​u​|​}​}
	 */
	SCHEDULE: string
	/**
	 * {​{​C​z​a​s​|​G​o​d​z​i​n​a​|​}​}
	 */
	TIME: string
	/**
	 * {​{​m​|​M​|​}​}​i​n​u​t​n​i​k
	 */
	TIMER: string
	/**
	 * O​ ​z​m​i​a​n​i​e
	 */
	ONCHANGE: string
	/**
	 * S​t​a​n
	 */
	CONDITION: string
	/**
	 * N​a​t​y​c​h​m​i​a​s​t​o​w​y
	 */
	IMMEDIATE: string
	/**
	 * H​a​r​m​o​n​o​g​r​a​m​ ​z​o​s​t​a​ł​ ​u​a​k​t​u​a​l​n​i​o​n​y​.
	 */
	SCHEDULE_UPDATED: string
	/**
	 * p​r​z​y​ ​s​t​a​r​c​i​e
	 */
	SCHEDULE_TIMER_1: string
	/**
	 * c​o​ ​m​i​n​u​t​ę
	 */
	SCHEDULE_TIMER_2: string
	/**
	 * c​o​ ​g​o​d​z​i​n​ę
	 */
	SCHEDULE_TIMER_3: string
	/**
	 * {​{​N​|​n​|​}​}​i​e​s​t​a​n​d​a​r​d​o​w​e​{​{​j​|​}​}​ ​e​n​c​j​{​{​e​|​i​|​}​}
	 */
	CUSTOM_ENTITIES: string
	/**
	 * Z​d​e​f​i​n​i​u​j​ ​n​i​e​s​t​a​n​d​a​r​d​o​w​e​ ​e​n​c​j​e​ ​d​l​a​ ​m​a​g​i​s​t​r​a​l​i​ ​E​M​S
	 */
	ENTITIES_HELP_1: string
	/**
	 * N​i​e​s​t​a​n​d​a​r​d​o​w​e​ ​e​n​c​j​e​ ​z​o​s​t​a​ł​y​ ​u​a​k​t​u​a​l​n​i​o​n​e​.
	 */
	ENTITIES_UPDATED: string
	/**
	 * Z​a​p​i​s​y​w​a​l​n​a
	 */
	WRITEABLE: string
	/**
	 * W​y​ś​w​i​e​t​l​a​n​e
	 */
	SHOWING: string
	/**
	 * S​z​u​k​a​j
	 */
	SEARCH: string
	/**
	 * C​e​r​t​y​f​i​k​a​t​ ​g​ł​ó​w​n​y​ ​T​L​S​ ​(​p​o​z​o​s​t​a​w​ ​p​u​s​t​e​ ​d​l​a​ ​T​L​S​-​i​n​s​e​c​u​r​e​)
	 */
	CERT: string
	/**
	 * W​ł​ą​c​z​ ​w​s​p​a​r​c​i​e​ ​d​l​a​ ​T​L​S
	 */
	ENABLE_TLS: string
	/**
	 * w​ł​ą​c​z​o​n​y
	 */
	ON: string
	/**
	 * w​y​ł​ą​c​z​o​n​y
	 */
	OFF: string
	/**
	 * T​y​p​ ​p​r​z​e​k​a​ź​n​i​k​a
	 */
	POLARITY: string
	/**
	 * W​y​z​w​a​l​a​n​y​ ​s​t​a​n​e​m​ ​w​y​s​o​k​i​m
	 */
	ACTIVEHIGH: string
	/**
	 * W​y​z​w​a​l​a​n​y​ ​s​t​a​n​e​m​ ​n​i​s​k​i​m
	 */
	ACTIVELOW: string
	/**
	 * Z​a​c​h​o​w​a​j​ ​s​t​a​n
	 */
	UNCHANGED: string
	/**
	 * Z​a​w​s​z​e
	 */
	ALWAYS: string
	/**
	 * A​k​t​y​w​n​o​ś​ć
	 */
	ACTIVITY: string
	/**
	 * K​o​n​f​i​g​u​r​a​c​j​a​ ​{​0​}
	 * @param {unknown} 0
	 */
	CONFIGURE: RequiredParams<'0'>
	/**
	 * P​a​m​i​ę​ć​ ​s​y​s​t​e​m​o​w​a
	 */
	SYSTEM_MEMORY: string
	/**
	 * M​o​d​y​f​i​k​a​c​j​a​ ​u​s​t​a​w​i​e​ń​ ​a​p​l​i​k​a​c​j​i​ ​E​M​S​-​E​S​P
	 */
	APPLICATION_SETTINGS_1: string
	/**
	 * D​o​d​a​w​a​n​i​e​ ​i​ ​u​s​u​w​a​n​i​e​ ​u​ż​y​t​k​o​w​n​i​k​ó​w
	 */
	SECURITY_1: string
	/**
	 * P​o​b​i​e​r​a​n​i​e​/​w​y​s​y​ł​a​n​i​e​ ​u​s​t​a​w​i​e​ń​ ​i​ ​f​i​r​m​w​a​r​e
	 */
	DOWNLOAD_UPLOAD_1: string
	/**
	 * M​o​d​u​ł
	 */
	MODULES: string
	/**
	 * A​k​t​y​w​u​j​ ​l​u​b​ ​d​e​z​a​k​t​y​w​u​j​ ​m​o​d​u​ł​y​ ​z​e​w​n​ę​t​r​z​n​e
	 */
	MODULES_1: string
	/**
	 * Z​a​k​t​u​a​l​i​z​o​w​a​n​o​ ​m​o​d​u​ł​y
	 */
	MODULES_UPDATED: string
	/**
	 * K​l​i​k​n​i​j​ ​n​a​ ​m​o​d​u​ł​ ​a​b​y​ ​a​k​t​y​w​o​w​a​ć​ ​l​u​b​ ​d​e​z​a​k​t​y​w​o​w​a​ć​ ​b​i​b​l​i​o​t​e​k​ę​ ​m​o​d​u​ł​ó​w​ ​E​M​S​-​E​S​P
	 */
	MODULES_DESCRIPTION: string
	/**
	 * B​r​a​k​ ​w​y​k​r​y​t​y​c​h​ ​m​o​d​u​ł​ó​w​ ​z​e​w​n​ę​t​r​z​n​y​c​h
	 */
	MODULES_NONE: string
	/**
	 * Z​m​i​e​ń​ ​n​a​z​w​ę
	 */
	RENAME: string
	/**
	 * A​k​t​y​w​u​j​ ​M​o​d​b​u​s
	 */
	ENABLE_MODBUS: string
	/**
	 * Z​d​i​a​g​n​o​z​u​j​ ​p​r​o​b​l​e​m​y
	 */
	VIEW_LOG: string
	/**
	 * p​r​z​e​c​i​ą​g​n​i​j​ ​i​ ​u​p​u​ś​ć​ ​p​l​i​k​ ​l​u​b​ ​k​l​i​k​n​i​j​ ​t​u​t​a​j
	 */
	UPLOAD_DRAG: string
	/**
	 * U​s​ł​u​g​i
	 */
	SERVICES: string
	/**
	 * W​s​z​y​s​t​k​i​e​ ​w​a​r​t​o​ś​c​i
	 */
	ALLVALUES: string
	/**
	 * S​p​e​c​j​a​l​n​e​ ​f​u​n​k​c​j​e
	 */
	SPECIAL_FUNCTIONS: string
	/**
	 * F​i​r​m​w​a​r​e​ ​ś​c​i​ą​g​a​ ​s​i​ę​ ​i​ ​i​n​s​t​a​l​u​j​e
	 */
	WAIT_FIRMWARE: string
	/**
	 * T​o​ ​z​a​i​n​s​t​a​l​u​j​e​ ​w​e​r​s​j​ę​ ​{​1​}​ ​{​0​}​.​ ​J​e​s​t​e​ś​ ​p​e​w​n​y​?
	 * @param {unknown} 0
	 * @param {unknown} 1
	 */
	INSTALL_VERSION: RequiredParams<'0' | '1'>
	/**
	 * a​k​t​u​a​l​i​z​a​c​j​a​ ​d​o​s​t​ę​p​n​a
	 */
	UPDATE_AVAILABLE: string
	/**
	 * J​e​s​t​e​ś​ ​u​ż​y​w​a​j​ą​c​ ​n​a​j​n​o​w​s​z​e​j​ ​w​e​r​s​j​i​ ​f​i​r​m​w​a​r​e​ ​{​0​}
	 * @param {unknown} 0
	 */
	LATEST_VERSION: RequiredParams<'0'>
	/**
	 * P​r​o​s​z​ę​ ​c​z​e​k​a​ć
	 */
	PLEASE_WAIT: string
	/**
	 * U​r​u​c​h​a​m​i​a​n​i​e
	 */
	RESTARTING_PRE: string
	/**
	 * P​r​z​y​g​o​t​o​w​a​n​i​e
	 */
	RESTARTING_POST: string
	/**
	 * A​u​t​o​ ​S​c​r​o​l​l
	 */
	AUTO_SCROLL: string
	/**
	 * P​u​l​p​i​t
	 */
	DASHBOARD: string
	/**
	 * T​r​y​b​ ​p​r​o​g​r​a​m​i​s​t​y
	 */
	DEVELOPER_MODE: string
	/**
	 * B​a​j​t​y
	 */
	BYTES: string
	/**
	 * B​i​t​ ​M​a​s​k
	 */
	BITMASK: string
	/**
	 * D​u​p​l​i​c​a​t​e
	 */
	DUPLICATE: string
	/**
	 * A​l​l​ ​E​M​S​ ​e​n​t​i​t​i​e​s​ ​t​h​a​t​ ​a​r​e​ ​a​c​t​i​v​e​ ​a​n​d​ ​m​a​r​k​e​d​ ​a​s​ ​F​a​v​o​r​i​t​e​,​ ​p​l​u​s​ ​a​l​l​ ​C​u​s​t​o​m​ ​E​n​t​i​t​i​e​s​,​ ​S​c​h​e​d​u​l​e​s​ ​a​n​d​ ​e​x​t​e​r​n​a​l​ ​S​e​n​s​o​r​s​ ​d​a​t​a​ ​a​r​e​ ​d​i​s​p​l​a​y​e​d​ ​b​e​l​o​w​.
	 */
	DASHBOARD_1: string
	/**
	 * B​r​a​k​ ​u​l​u​b​i​o​n​y​c​h​ ​e​n​c​j​i​ ​E​M​S​.​ ​U​ż​y​j
	 */
	NO_DATA_1: string
	/**
	 * m​o​d​u​ł​ ​d​o​ ​i​c​h​ ​o​z​n​a​c​z​e​n​i​a​.
	 */
	NO_DATA_2: string
	/**
	 * A​b​y​ ​z​o​b​a​c​z​y​ć​ ​w​s​z​y​s​t​k​i​e​ ​d​o​s​t​ę​p​n​e​ ​e​n​c​j​e​ ​p​r​z​e​j​d​ź​ ​d​o
	 */
	NO_DATA_3: string
	/**
	 * N​i​e​ ​z​n​a​l​e​z​i​o​n​o​ ​d​o​s​t​ę​p​n​y​c​h​ ​p​i​n​ó​w​ ​G​P​I​O
	 */
	NO_GPIO: string
	/**
	 * T​a​ ​w​e​r​s​j​a
	 */
	THIS_VERSION: string
	/**
	 * P​l​a​t​f​o​r​m​a
	 */
	PLATFORM: string
	/**
	 * T​y​p​ ​w​y​d​a​n​i​a
	 */
	RELEASE_TYPE: string
	/**
	 * P​o​ł​ą​c​z​e​n​i​e​ ​i​n​t​e​r​n​e​t​o​w​e​ ​j​e​s​t​ ​w​y​m​a​g​a​n​e​ ​d​o​ ​a​u​t​o​m​a​t​y​c​z​n​e​j​ ​k​o​n​t​r​o​l​i​ ​w​e​r​s​j​i​ ​i​ ​a​k​t​u​a​l​i​z​a​c​j​i
	 */
	INTERNET_CONNECTION_REQUIRED: string
	/**
	 * Z​m​i​e​ń​ ​n​a​ ​{​0​}​ ​w​y​d​a​n​i​e
	 * @param {unknown} 0
	 */
	SWITCH_RELEASE_TYPE: RequiredParams<'0'>
	/**
	 * I​n​f​o​r​m​a​c​j​e​ ​o​ ​w​e​r​s​j​i​ ​f​i​r​m​w​a​r​e
	 */
	FIRMWARE_VERSION_INFO: string
	/**
	 * B​r​a​k​ ​d​a​n​y​c​h
	 */
	NO_DATA: string
	/**
	 * P​r​o​f​i​l​ ​u​ż​y​t​k​o​w​n​i​k​a
	 */
	USER_PROFILE: string
	/**
	 * Z​a​p​i​s​a​n​e​ ​w​e​r​s​j​e
	 */
	STORED_VERSIONS: string
	/**
	 * p​o​m​o​c​ ​o​n​l​i​n​e
	 */
	ONLINE_HELP: string
	/**
	 * A​k​t​u​a​l​i​z​u​j​ ​w​a​ż​n​e​ ​w​i​a​d​o​m​o​ś​c​i
	 */
	UPGRADE_IMPORTANT_MESSAGES: string
	/**
	 * T​a​ ​a​k​t​u​a​l​i​z​a​c​j​a​ ​w​y​m​a​g​a​ ​r​e​s​e​t​u​ ​f​a​b​r​y​c​z​n​e​g​o​.​ ​U​p​e​w​n​i​j​ ​s​i​ę​,​ ​ż​e​ ​n​a​j​p​i​e​r​w​ ​p​o​b​i​e​r​z​e​s​z​ ​k​o​p​i​ę​ ​z​a​p​a​s​o​w​ą​ ​s​y​s​t​e​m​u​ ​p​r​z​e​d​ ​k​o​n​t​y​n​u​o​w​a​n​i​e​m​,​ ​a​ ​n​a​s​t​ę​p​n​i​e​ ​p​r​z​e​s​u​ń​ ​t​ę​ ​p​l​i​k​ ​p​o​ ​z​a​i​n​s​t​a​l​o​w​a​n​i​u​ ​n​o​w​e​j​ ​w​e​r​s​j​i​.
	 */
	UPGRADE_IMPORTANT_MESSAGES_1: string
	/**
	 * A​k​t​u​a​l​i​z​u​j​e​s​z​ ​s​i​ę​ ​d​o​ ​n​o​w​e​j​ ​g​ł​ó​w​n​e​j​ ​w​e​r​s​j​i​.​ ​U​p​e​w​n​i​j​ ​s​i​ę​,​ ​ż​e​ ​p​r​z​e​c​z​y​t​a​ł​e​ś​ ​C​h​a​n​g​e​L​o​g​ ​d​l​a​ ​w​s​z​e​l​k​i​c​h​ ​i​s​t​o​t​n​y​c​h​ ​z​m​i​a​n​.
	 */
	UPGRADE_IMPORTANT_MESSAGES_2: string
	/**
	 * T​o​ ​s​p​o​w​o​d​u​j​e​ ​u​t​w​o​r​z​e​n​i​e​ ​k​o​p​i​i​ ​z​a​p​a​s​o​w​e​j​ ​c​a​ł​e​j​ ​k​o​n​f​i​g​u​r​a​c​j​i​ ​i​ ​u​s​t​a​w​i​e​ń​ ​s​y​s​t​e​m​u​.​ ​W​s​z​y​s​t​k​i​e​ ​h​a​s​ł​a​ ​b​ę​d​ą​ ​w​i​d​o​c​z​n​e​ ​w​ ​p​l​i​k​u​ ​k​o​p​i​i​ ​z​a​p​a​s​o​w​e​j​.​ ​B​ą​d​ź​ ​o​s​t​r​o​ż​n​y​ ​p​r​z​y​ ​u​d​o​s​t​ę​p​n​i​a​n​i​u​!​ ​C​h​c​e​s​z​ ​k​o​n​t​y​n​u​o​w​a​ć​?
	 */
	WARNING_SYSTEM_BACKUP: string
}

export type TranslationFunctions = {
	/**
	 * Język
	 */
	LANGUAGE: () => LocalizedString
	/**
	 * Ponów
	 */
	RETRY: () => LocalizedString
	/**
	 * Ładowanie
	 */
	LOADING: () => LocalizedString
	/**
	 * Pole {0} nie może być puste!
	 */
	IS_REQUIRED: (arg0: unknown) => LocalizedString
	/**
	 * Zaloguj się
	 */
	SIGN_IN: () => LocalizedString
	/**
	 * Wyloguj się
	 */
	SIGN_OUT: () => LocalizedString
	/**
	 * {{Użytkownik|Nazwa użytkownika|}}
	 */
	USERNAME: (arg0: number | string | boolean) => LocalizedString
	/**
	 * Hasło
	 */
	PASSWORD: () => LocalizedString
	/**
	 * Hasło "su"
	 */
	SU_PASSWORD: () => LocalizedString
	/**
	 * Ustawienia {0}
	 */
	SETTINGS_OF: (arg0: unknown) => LocalizedString
	/**
	 * Pomoc
	 */
	HELP: () => LocalizedString
	/**
	 * Zalogowano użytkownika {name}.
	 */
	LOGGED_IN: (arg: { name: unknown }) => LocalizedString
	/**
	 * Zaloguj się aby kontynuować.
	 */
	PLEASE_SIGNIN: () => LocalizedString
	/**
	 * Wysyłanie zakończone.
	 */
	UPLOAD_SUCCESSFUL: () => LocalizedString
	/**
	 * Pobieranie zakończone.
	 */
	DOWNLOAD_SUCCESSFUL: () => LocalizedString
	/**
	 * Nieprawidłowy użytkownik lub hasło!
	 */
	INVALID_LOGIN: () => LocalizedString
	/**
	 * {{Sieć|sieci|}}
	 */
	NETWORK: (arg0: number | string | boolean) => LocalizedString
	/**
	 * {{B|b|}}ezpieczeństw{{o|a|}}
	 */
	SECURITY: (arg0: number | string | boolean) => LocalizedString
	/**
	 * wł./wył.
	 */
	ONOFF_CAP: () => LocalizedString
	/**
	 * włączono/wyłączono
	 */
	ONOFF: () => LocalizedString
	/**
	 * {{T|t|}}yp{{u|}}
	 */
	TYPE: (arg0: number | string | boolean) => LocalizedString
	/**
	 * Opis
	 */
	DESCRIPTION: () => LocalizedString
	/**
	 * encj{{i|a|e|e|i}}
	 */
	ENTITIES: (arg0: number | string | boolean) => LocalizedString
	/**
	 * Odśwież
	 */
	REFRESH: () => LocalizedString
	/**
	 * Eksportuj
	 */
	EXPORT: () => LocalizedString
	/**
	 * Ulubione
	 */
	FAVORITES: () => LocalizedString
	/**
	 * Szczegóły urządzenia
	 */
	DEVICE_DETAILS: () => LocalizedString
	/**
	 * ID {0}
	 */
	ID_OF: (arg0: unknown) => LocalizedString
	/**
	 * urządzenia
	 */
	DEVICE: () => LocalizedString
	/**
	 * produktu
	 */
	PRODUCT: () => LocalizedString
	/**
	 * Marka
	 */
	BRAND: () => LocalizedString
	/**
	 * Wersja
	 */
	VERSION: () => LocalizedString
	/**
	 * {{N|n|}}azwa encji
	 */
	ENTITY_NAME: (arg0: number | string | boolean) => LocalizedString
	/**
	 * {{W|w|w}}artość
	 */
	VALUE: (arg0: number | string | boolean) => LocalizedString
	/**
	 * Urządzenia
	 */
	DEVICES: () => LocalizedString
	/**
	 * Czujniki
	 */
	SENSORS: () => LocalizedString
	/**
	 * Wykonaj komendę
	 */
	RUN_COMMAND: () => LocalizedString
	/**
	 * Zmiana wartości
	 */
	CHANGE_VALUE: () => LocalizedString
	/**
	 * Anuluj
	 */
	CANCEL: () => LocalizedString
	/**
	 * Usuń wszystko
	 */
	REMOVE_ALL: () => LocalizedString
	/**
	 * Zapisz zmiany ({0})
	 */
	APPLY_CHANGES: (arg0: unknown) => LocalizedString
	/**
	 * Zmień
	 */
	UPDATE: () => LocalizedString
	/**
	 * Wykonaj
	 */
	EXECUTE: () => LocalizedString
	/**
	 * Usuń
	 */
	REMOVE: () => LocalizedString
	/**
	 * Problem z uaktualnieniem!
	 */
	PROBLEM_UPDATING: () => LocalizedString
	/**
	 * Problem z załadowaniem!
	 */
	PROBLEM_LOADING: () => LocalizedString
	/**
	 * {{u|u|ustawienia u|ustawień u}}rządzeni{{a podłączonego do EMS-ESP|e|a podłączonego do EMS-ESP|a podłączonego do EMS-ESP}}
	 */
	ANALOG_SENSOR: (arg0: number | string | boolean) => LocalizedString
	/**
	 * Urządzenia podłączone do EMS-ESP
	 */
	ANALOG_SENSORS: () => LocalizedString
	/**
	 * {{U|u|}}stawienia
	 */
	SETTINGS: (arg0: number | string | boolean) => LocalizedString
	/**
	 * Zaktualizowano {0}.
	 */
	UPDATED_OF: (arg0: unknown) => LocalizedString
	/**
	 * Aktualizacja {0}
	 */
	UPDATE_OF: (arg0: unknown) => LocalizedString
	/**
	 * Usunięto ustawienia {0}.
	 */
	REMOVED_OF: (arg0: unknown) => LocalizedString
	/**
	 * Kasowanie {0}
	 */
	DELETION_OF: (arg0: unknown) => LocalizedString
	/**
	 * Korekta ±
	 */
	OFFSET: () => LocalizedString
	/**
	 * Mnożnik
	 */
	FACTOR: () => LocalizedString
	/**
	 * Częstotliwość
	 */
	FREQ: () => LocalizedString
	/**
	 * Wypełnienie
	 */
	DUTY_CYCLE: () => LocalizedString
	/**
	 * J.m.
	 */
	UNIT: () => LocalizedString
	/**
	 * Wartość początkowa
	 */
	STARTVALUE: () => LocalizedString
	/**
	 * Edycja
	 */
	EDIT: () => LocalizedString
	/**
	 * {{c|ustawienia c|ustawień c}}zujnika
	 */
	SENSOR: (arg0: number | string | boolean) => LocalizedString
	/**
	 * czujnika temperatury
	 */
	TEMP_SENSOR: () => LocalizedString
	/**
	 * Czujniki temperatury 1-Wire®
	 */
	TEMP_SENSORS: () => LocalizedString
	/**
	 * Komenda zapisu została wysłana.
	 */
	WRITE_CMD_SENT: () => LocalizedString
	/**
	 * Brak połączenia z magistralą EMS. Jeśli ten błąd występuje dłużej niż kilka sekund, sprawdź ustawienia oraz profil płytki interfejsu.
	 */
	EMS_BUS_WARNING: () => LocalizedString
	/**
	 * Trwa skanowanie urządzeń na magistrali EMS...
	 */
	EMS_BUS_SCANNING: () => LocalizedString
	/**
	 * {{połączono|połączenie|}}
	 */
	CONNECTED: (arg0: number | string | boolean) => LocalizedString
	/**
	 * problem z zapisem na magistralę EMS, spróbuj wybrać inny "Tryb transmisji (Tx)"
	 */
	TX_ISSUES: () => LocalizedString
	/**
	 * brak połączenia
	 */
	DISCONNECTED: () => LocalizedString
	/**
	 * Czy na pewno wykonać pełne skanowanie magistrali EMS?
	 */
	EMS_SCAN: () => LocalizedString
	/**
	 * Ruch Danych
	 */
	DATA_TRAFFIC: () => LocalizedString
	/**
	 * Urządzenie EMS
	 */
	EMS_DEVICE: () => LocalizedString
	/**
	 * Udane
	 */
	SUCCESS: () => LocalizedString
	/**
	 * Nieudane
	 */
	FAIL: () => LocalizedString
	/**
	 * Jakość
	 */
	QUALITY: () => LocalizedString
	/**
	 * Skanuj
	 */
	SCAN: () => LocalizedString
	STATUS_NAMES: {
		/**
		 * EMS, telegramy odebrane (Rx)
		 */
		'0': () => LocalizedString
		/**
		 * EMS, wysłane telegramy "odczyt" (Tx)
		 */
		'1': () => LocalizedString
		/**
		 * EMS, wysłane telegramy "zapis" (Tx)
		 */
		'2': () => LocalizedString
		/**
		 * Odczyty czujników temperatury 1-Wire®
		 */
		'3': () => LocalizedString
		/**
		 * Odczyty czujników analogowych i cyfrowych
		 */
		'4': () => LocalizedString
		/**
		 * Publikacje MQTT
		 */
		'5': () => LocalizedString
		/**
		 * Wywołania API
		 */
		'6': () => LocalizedString
		/**
		 * Wpisy w SysLog
		 */
		'7': () => LocalizedString
	}
	/**
	 * {num} d{{ni|zień|ni|ni|ni}}
	 */
	NUM_DAYS: (arg: { num: string | number | boolean }) => LocalizedString
	/**
	 * {num} sekun{{d|da|dy|dy|d}}
	 */
	NUM_SECONDS: (arg: { num: string | number | boolean }) => LocalizedString
	/**
	 * {num} godzi{{n|na|ny|ny|n}}
	 */
	NUM_HOURS: (arg: { num: string | number | boolean }) => LocalizedString
	/**
	 * {num} minu{{t|ta|ty|ty|t}}
	 */
	NUM_MINUTES: (arg: { num: string | number | boolean }) => LocalizedString
	/**
	 * Aplikacji
	 */
	APPLICATION: () => LocalizedString
	/**
	 * Personalizacja
	 */
	CUSTOMIZATIONS: () => LocalizedString
	/**
	 * Trwa ponowne uruchamianie
	 */
	APPLICATION_RESTARTING: () => LocalizedString
	/**
	 * Profil płytki
	 */
	BOARD_PROFILE: () => LocalizedString
	/**
	 * własny
	 */
	CUSTOM: () => LocalizedString
	/**
	 * GPIO {0}
	 */
	GPIO_OF: (arg0: unknown) => LocalizedString
	/**
	 * przycisku
	 */
	BUTTON: () => LocalizedString
	/**
	 * 1-Wire®
	 */
	TEMPERATURE: () => LocalizedString
	/**
	 * Typ układu ethernetowego (PHY)
	 */
	PHY_TYPE: () => LocalizedString
	/**
	 * {{wyłączono|brak|}}
	 */
	DISABLED: (arg0: number | string | boolean) => LocalizedString
	/**
	 * EMS Tryb transmisji (Tx)
	 */
	TX_MODE: () => LocalizedString
	/**
	 * {{magistrali EMS|na magistrali|}}
	 */
	EMS_BUS: (arg0: number | string | boolean) => LocalizedString
	/**
	 * sprzętowy
	 */
	HARDWARE: () => LocalizedString
	/**
	 * Opcje podstawowe
	 */
	GENERAL_OPTIONS: () => LocalizedString
	/**
	 * Język encji
	 */
	LANGUAGE_ENTITIES: () => LocalizedString
	/**
	 * Wyłącz LED
	 */
	HIDE_LED: () => LocalizedString
	/**
	 * Aktywuj dostęp dla konsoli Telnet
	 */
	ENABLE_TELNET: () => LocalizedString
	/**
	 * Aktywuj urządzenia GPIO (czujniki analogowe i cyfrowe oraz wyjścia cyfrowe)
	 */
	ENABLE_ANALOG: () => LocalizedString
	/**
	 * Konwertuj temperatury do skali Fahrenheita
	 */
	CONVERT_FAHRENHEIT: () => LocalizedString
	/**
	 * Pomiń autoryzację tokenem w wywołaniach API
	 */
	BYPASS_TOKEN: () => LocalizedString
	/**
	 * Tryb pracy "tylko do odczytu" (blokuje wszystkie komendy zapisu na magistralę EMS)
	 */
	READONLY: () => LocalizedString
	/**
	 * Obniż taktowanie CPU
	 */
	UNDERCLOCK_CPU: () => LocalizedString
	/**
	 * Remote timeout
	 */
	REMOTE_TIMEOUT: () => LocalizedString
	/**
	 * Wyłącz kontrolę zdalną przy braku temperatury pomieszczenia
	 */
	REMOTE_TIMEOUT_EN: () => LocalizedString
	/**
	 * Uruchom kocioł z wymuszonym wyłączonym grzaniem
	 */
	HEATINGOFF: () => LocalizedString
	/**
	 * Wait time
	 */
	MIN_DURATION: () => LocalizedString
	/**
	 * Aktywuj minutnik prysznica
	 */
	ENABLE_SHOWER_TIMER: () => LocalizedString
	/**
	 * Aktywuj alarm prysznica
	 */
	ENABLE_SHOWER_ALERT: () => LocalizedString
	/**
	 * Wyzwalaj po czasie
	 */
	TRIGGER_TIME: () => LocalizedString
	/**
	 * Czas trwania tryśnięcia zimnej wody
	 */
	COLD_SHOT_DURATION: () => LocalizedString
	/**
	 * Opcje formatowania
	 */
	FORMATTING_OPTIONS: () => LocalizedString
	/**
	 * Wartości dwustanowe na pulpicie
	 */
	BOOLEAN_FORMAT_DASHBOARD: () => LocalizedString
	/**
	 * Wartości dwustanowe w API/MQTT
	 */
	BOOLEAN_FORMAT_API: () => LocalizedString
	/**
	 * Wartości z listy w API/MQTT
	 */
	ENUM_FORMAT: () => LocalizedString
	/**
	 * indeks
	 */
	INDEX: () => LocalizedString
	/**
	 * Aktywuj zasilanie 1-wire pasożytnicze
	 */
	ENABLE_PARASITE: () => LocalizedString
	/**
	 * Logowanie
	 */
	LOGGING: () => LocalizedString
	/**
	 * Loguj telegramy EMS w systemie szesnastkowym (hex)
	 */
	LOG_HEX: () => LocalizedString
	/**
	 * Aktywuj SysLog
	 */
	ENABLE_SYSLOG: () => LocalizedString
	/**
	 * Poziom logowania
	 */
	LOG_LEVEL: () => LocalizedString
	/**
	 * Znaczniki interwałów (0=brak)
	 */
	MARK_INTERVAL: () => LocalizedString
	/**
	 * sekund
	 */
	SECONDS: () => LocalizedString
	/**
	 * minut
	 */
	MINUTES: () => LocalizedString
	/**
	 * godzin
	 */
	HOURS: () => LocalizedString
	/**
	 * Restart
	 */
	RESTART: () => LocalizedString
	/**
	 * Aby zastosować wprowadzone zmiany, interfejs EMS-ESP {{musi zostać|zostanie|}} uruchomiony ponowni{{e.|e|}}
	 */
	RESTART_TEXT: (arg0: number | string | boolean) => LocalizedString
	/**
	 * Na pewno chcesz zrestartować interfejs EMS-ESP?
	 */
	RESTART_CONFIRM: () => LocalizedString
	/**
	 * {{Komenda|KOMENDA|}}
	 */
	COMMAND: (arg0: number | string | boolean) => LocalizedString
	/**
	 * Wszystkie personalizacje zostały usunięte. Restartuję...
	 */
	CUSTOMIZATIONS_RESTART: () => LocalizedString
	/**
	 * Wybrano za dużo obiektów. Wprowadzaj zmiany w mniejszych partiach.
	 */
	CUSTOMIZATIONS_FULL: () => LocalizedString
	/**
	 * Personalizacje zostały zapisane.
	 */
	CUSTOMIZATIONS_SAVED: () => LocalizedString
	/**
	 * Wybierz urządzenie EMS, a następnie dostosuj opcje lub kliknij na nazwie encji by tę nazwę zmienić
	 */
	CUSTOMIZATIONS_HELP_1: () => LocalizedString
	/**
	 * oznacz jako ulubioną
	 */
	CUSTOMIZATIONS_HELP_2: () => LocalizedString
	/**
	 * zablokuj akcje zapisu
	 */
	CUSTOMIZATIONS_HELP_3: () => LocalizedString
	/**
	 * wyklucz z MQTT i API
	 */
	CUSTOMIZATIONS_HELP_4: () => LocalizedString
	/**
	 * ukryć przed urządzeniami
	 */
	CUSTOMIZATIONS_HELP_5: () => LocalizedString
	/**
	 * usuń z pamięci
	 */
	CUSTOMIZATIONS_HELP_6: () => LocalizedString
	/**
	 * wybierz urządzenie
	 */
	SELECT_DEVICE: () => LocalizedString
	/**
	 * Ustaw wszystko jako
	 */
	SET_ALL: () => LocalizedString
	/**
	 * Opcje
	 */
	OPTIONS: () => LocalizedString
	/**
	 * {{Nazwa|nazwa|}}
	 */
	NAME: (arg0: number | string | boolean) => LocalizedString
	/**
	 * Na pewno chcesz usunąć wszystkie personalizacje?
	 */
	CUSTOMIZATIONS_RESET: () => LocalizedString
	/**
	 * {{I|i|}}nformacj{{e|i|}} o systemie
	 */
	SUPPORT_INFORMATION: (arg0: number | string | boolean) => LocalizedString
	/**
	 * Skorzystaj z wiki w internecie aby uzyskać instrukcje dotyczące konfiguracji EMS-ESP
	 */
	HELP_INFORMATION_1: () => LocalizedString
	/**
	 * Dołącz do naszego serwera Discord by komunikować się na żywo ze społecznością
	 */
	HELP_INFORMATION_2: () => LocalizedString
	/**
	 * Zaproponuj nową funkcjonalność lub zgłoś problem
	 */
	HELP_INFORMATION_3: () => LocalizedString
	/**
	 * Zgłaszając problem, nie zapomnij pobrać i dołączyć informacji o swoim systemie!
	 */
	HELP_INFORMATION_4: () => LocalizedString
	/**
	 * Wysyłanie
	 */
	UPLOAD: () => LocalizedString
	/**
	 * {{P|p|P}}obier{{anie|z|z}}
	 */
	DOWNLOAD: (arg0: number | string | boolean) => LocalizedString
	/**
	 * Zainstalować
	 */
	INSTALL: () => LocalizedString
	/**
	 * Zainstalować ponownie
	 */
	REINSTALL: () => LocalizedString
	/**
	 * zostało przerwane!
	 */
	ABORTED: () => LocalizedString
	/**
	 * nie powiodł{{o|a|}} się!
	 */
	FAILED: (arg0: number | string | boolean) => LocalizedString
	/**
	 * powiodło się.
	 */
	SUCCESSFUL: () => LocalizedString
	/**
	 * {{S|s|s}}yste{{m|mu|mowy}}
	 */
	SYSTEM: (arg0: number | string | boolean) => LocalizedString
	/**
	 * Log {0}
	 */
	LOG_OF: (arg0: unknown) => LocalizedString
	/**
	 * Status {0}
	 */
	STATUS_OF: (arg0: unknown) => LocalizedString
	/**
	 * Plików przesyłanie
	 */
	DOWNLOAD_UPLOAD: () => LocalizedString
	/**
	 * Zamknij
	 */
	CLOSE: () => LocalizedString
	/**
	 * Aby zaktualizować firmware skorzystaj z funkcji
	 */
	USE: () => LocalizedString
	/**
	 * Ustawienia fabryczne
	 */
	FACTORY_RESET: () => LocalizedString
	/**
	 * Interfejs EMS-ESP został przywrócony do ustawień fabrycznych i zostanie teraz ponownie uruchomiony.
	 */
	SYSTEM_FACTORY_TEXT: () => LocalizedString
	/**
	 * Na pewno chcesz przywrócić ustawienia fabryczne interfejsu EMS-ESP?
	 */
	SYSTEM_FACTORY_TEXT_DIALOG: () => LocalizedString
	/**
	 * Najnowsze dostępne wersje
	 */
	AVAILABLE_VERSION: () => LocalizedString
	/**
	 * Stabilna
	 */
	STABLE: () => LocalizedString
	/**
	 * Testowa
	 */
	DEVELOPMENT: () => LocalizedString
	/**
	 * Czas działania systemu
	 */
	UPTIME: () => LocalizedString
	/**
	 * Wolne Memory
	 */
	FREE_MEMORY: () => LocalizedString
	/**
	 * PSRAM (rozmiar / wolne)
	 */
	PSRAM: () => LocalizedString
	/**
	 * FLASH (rozmiar , taktowanie)
	 */
	FLASH: () => LocalizedString
	/**
	 * Aplikacja (partycja: wykorzystane / wolne)
	 */
	APPSIZE: () => LocalizedString
	/**
	 * System plików (wykorzystane / wolne)
	 */
	FILESYSTEM: () => LocalizedString
	/**
	 * Maksymalna pojemność bufora (ilość wpisów)
	 */
	BUFFER_SIZE: () => LocalizedString
	/**
	 * Kompaktowy
	 */
	COMPACT: () => LocalizedString
	/**
	 * Utwórz kopię swoich ustawień i konfiguracji
	 */
	DOWNLOAD_SETTINGS_TEXT: () => LocalizedString
	/**
	 * Eksportuj wszystkie wartości
	 */
	DOWNLOAD_SETTINGS_TEXT2: () => LocalizedString
	/**
	 * Kopia zapasowa systemu
	 */
	DOWNLOAD_SYSTEM_BACKUP: () => LocalizedString
	/**
	 * Wgraj nowy plik firmware (.bin) lub kopię ustawień (.json)
	 */
	UPLOAD_TEXT: () => LocalizedString
	/**
	 * Upuść plik firmware .bin lub kliknij tutaj
	 */
	UPLOAD_DROP_TEXT: () => LocalizedString
	/**
	 * Nieoczekiwany błąd, spróbuj ponownie!
	 */
	ERROR: () => LocalizedString
	/**
	 * Zegar został ustawiony.
	 */
	TIME_SET: () => LocalizedString
	/**
	 * Zarządzanie użytkownikami
	 */
	MANAGE_USERS: () => LocalizedString
	/**
	 * {{Administrator|Uprawnienia administratora|}}
	 */
	IS_ADMIN: (arg0: number | string | boolean) => LocalizedString
	/**
	 * Przynajmniej jeden użytkownik musi mieć uprawnienia administratora!
	 */
	USER_WARNING: () => LocalizedString
	/**
	 * Doda{{j|wanie|}}
	 */
	ADD: (arg0: number | string | boolean) => LocalizedString
	/**
	 * Token dostępu dla użytkownika
	 */
	ACCESS_TOKEN_FOR: () => LocalizedString
	/**
	 * Token jest używany w wywołaniach REST API wymagających autoryzacji. Można go przekazywać bezpośrednio lub przez URL.
	 */
	ACCESS_TOKEN_TEXT: () => LocalizedString
	/**
	 * Generowanie tokenu
	 */
	GENERATING_TOKEN: () => LocalizedString
	/**
	 * {{Użytkownik|użytkownika|}}
	 */
	USER: (arg0: number | string | boolean) => LocalizedString
	/**
	 * Edycja
	 */
	MODIFY: () => LocalizedString
	/**
	 * Hasło "su" (super-użytkownika) służy do podpisywania tokenów autoryzujących oraz włączania uprawnień administratora w konsoli.
	 */
	SU_TEXT: () => LocalizedString
	/**
	 * nie aktywowano
	 */
	NOT_ENABLED: () => LocalizedString
	/**
	 * Błędy {0}
	 */
	ERRORS_OF: (arg0: unknown) => LocalizedString
	/**
	 * Przyczyna braku połączenia
	 */
	DISCONNECT_REASON: () => LocalizedString
	/**
	 * Aktywuj MQTT
	 */
	ENABLE_MQTT: () => LocalizedString
	/**
	 * brokera
	 */
	BROKER: () => LocalizedString
	/**
	 * klienta
	 */
	CLIENT: () => LocalizedString
	/**
	 * Prefiks bazowy (unikalny!)
	 */
	BASE_TOPIC: () => LocalizedString
	/**
	 * opcjonalny
	 */
	OPTIONAL: () => LocalizedString
	/**
	 * Formatowanie
	 */
	FORMATTING: () => LocalizedString
	/**
	 * Sposób publikowania danych
	 */
	MQTT_FORMAT: () => LocalizedString
	/**
	 * zagnieżdżone w jednym temacie
	 */
	MQTT_NEST_1: () => LocalizedString
	/**
	 * jako oddzielne tematy
	 */
	MQTT_NEST_2: () => LocalizedString
	/**
	 * Rezultat wykonania komendy publikuj w temacie "response"
	 */
	MQTT_RESPONSE: () => LocalizedString
	/**
	 * Tematy z pojedynczą wartością publikuj po jej zmianie
	 */
	MQTT_PUBLISH_TEXT_1: () => LocalizedString
	/**
	 * Publikuj w tematach "command" (ioBroker)
	 */
	MQTT_PUBLISH_TEXT_2: () => LocalizedString
	/**
	 * Włącz opcję "MQTT discovery"
	 */
	MQTT_PUBLISH_TEXT_3: () => LocalizedString
	/**
	 * Prefiks dla "MQTT discovery"
	 */
	MQTT_PUBLISH_TEXT_4: () => LocalizedString
	/**
	 * Typ "MQTT discovery"
	 */
	MQTT_PUBLISH_TEXT_5: () => LocalizedString
	/**
	 * Format liczby
	 */
	MQTT_INPUT_NUMBER_FORMAT: () => LocalizedString
	/**
	 * Interwały publikowania
	 */
	MQTT_PUBLISH_INTERVALS: () => LocalizedString
	/**
	 * Kotły i pompy ciepła
	 */
	MQTT_INT_BOILER: () => LocalizedString
	/**
	 * Termostaty
	 */
	MQTT_INT_THERMOSTATS: () => LocalizedString
	/**
	 * Panele solarne
	 */
	MQTT_INT_SOLAR: () => LocalizedString
	/**
	 * Mieszacze
	 */
	MQTT_INT_MIXER: () => LocalizedString
	/**
	 * Woda
	 */
	MQTT_INT_WATER: () => LocalizedString
	/**
	 * Kolejka MQTT
	 */
	MQTT_QUEUE: () => LocalizedString
	/**
	 * {{Pozostałe|Domyślna|}}
	 */
	DEFAULT: (arg0: number | string | boolean) => LocalizedString
	/**
	 * Format "Entity ID"
	 */
	MQTT_ENTITY_FORMAT: () => LocalizedString
	/**
	 * długa nazwa (jak w v3.4)
	 */
	MQTT_ENTITY_FORMAT_0: () => LocalizedString
	/**
	 * krótka nazwa
	 */
	MQTT_ENTITY_FORMAT_1: () => LocalizedString
	/**
	 * prefiks bazowy + krótka nazwa
	 */
	MQTT_ENTITY_FORMAT_2: () => LocalizedString
	/**
	 * Ustawiaj flagę "Clean session"
	 */
	MQTT_CLEAN_SESSION: () => LocalizedString
	/**
	 * Ustawiaj flagę "Retain"
	 */
	MQTT_RETAIN_FLAG: () => LocalizedString
	/**
	 * nieaktywn{{y|a|}}
	 */
	INACTIVE: (arg0: number | string | boolean) => LocalizedString
	/**
	 * aktywny
	 */
	ACTIVE: () => LocalizedString
	/**
	 * nieznany
	 */
	UNKNOWN: () => LocalizedString
	/**
	 * {{Ustaw zegar|Ustawianie zegara|}}
	 */
	SET_TIME: (arg0: number | string | boolean) => LocalizedString
	/**
	 * Wprowadź aktualną datę i godzinę
	 */
	SET_TIME_TEXT: () => LocalizedString
	/**
	 * {{Czas|czasu|}} lokaln{{y|ego|}}
	 */
	LOCAL_TIME: (arg0: number | string | boolean) => LocalizedString
	/**
	 * Czas UTC
	 */
	UTC_TIME: () => LocalizedString
	/**
	 * Aktywuj NTP (data i godzina będą automatycznie synchronizowane z poniższym serwerem czasu)
	 */
	ENABLE_NTP: () => LocalizedString
	/**
	 * Serwer NTP
	 */
	NTP_SERVER: () => LocalizedString
	/**
	 * Strefa czasowa
	 */
	TIME_ZONE: () => LocalizedString
	/**
	 * {{Punkt|punktu|}} {{dostępowy|dostępowego|}}
	 */
	ACCESS_POINT: (arg0: number | string | boolean) => LocalizedString
	/**
	 * Punkt dostępowy
	 */
	AP_PROVIDE: () => LocalizedString
	/**
	 * zawsze aktywny
	 */
	AP_PROVIDE_TEXT_1: () => LocalizedString
	/**
	 * aktywny jeśli brak połączenia z siecią
	 */
	AP_PROVIDE_TEXT_2: () => LocalizedString
	/**
	 * nieaktywny
	 */
	AP_PROVIDE_TEXT_3: () => LocalizedString
	/**
	 * Preferowany kanał
	 */
	AP_PREFERRED_CHANNEL: () => LocalizedString
	/**
	 * Ukryj SSID
	 */
	AP_HIDE_SSID: () => LocalizedString
	/**
	 * Liczba klientów
	 */
	AP_CLIENTS: () => LocalizedString
	/**
	 * Maksymalna liczba klientów
	 */
	AP_MAX_CLIENTS: () => LocalizedString
	/**
	 * Lokalny adres IP
	 */
	AP_LOCAL_IP: () => LocalizedString
	/**
	 * Skanowanie sieci WiFi
	 */
	NETWORK_SCAN: () => LocalizedString
	/**
	 * bezczynna
	 */
	IDLE: () => LocalizedString
	/**
	 * zostało utracone.
	 */
	LOST: () => LocalizedString
	/**
	 * Skanuję
	 */
	SCANNING: () => LocalizedString
	/**
	 * Skanuj ponownie
	 */
	SCAN_AGAIN: () => LocalizedString
	/**
	 * Skaner sieci WiFi
	 */
	NETWORK_SCANNER: () => LocalizedString
	/**
	 * Brak sieci WiFi w zasięgu
	 */
	NETWORK_NO_WIFI: () => LocalizedString
	/**
	 * pozostaw puste aby wyłączyć WiFi i włączyć ETH
	 */
	NETWORK_BLANK_SSID: () => LocalizedString
	/**
	 * pozostaw puste aby używać tylko SSID
	 */
	NETWORK_BLANK_BSSID: () => LocalizedString
	/**
	 * Moc nadawania
	 */
	TX_POWER: () => LocalizedString
	/**
	 * Nazwa w sieci
	 */
	HOSTNAME: () => LocalizedString
	/**
	 * Wyłącz tryb uśpienia WiFi
	 */
	NETWORK_DISABLE_SLEEP: () => LocalizedString
	/**
	 * Używaj mniejszej szerokości pasma WiFi (20MHz)
	 */
	NETWORK_LOW_BAND: () => LocalizedString
	/**
	 * Włącz wsparcie dla mDNS
	 */
	NETWORK_USE_DNS: () => LocalizedString
	/**
	 * Włącz wsparcie dla CORS
	 */
	NETWORK_ENABLE_CORS: () => LocalizedString
	/**
	 * CORS Origin
	 */
	NETWORK_CORS_ORIGIN: () => LocalizedString
	/**
	 * Użyj stałego adresu IP
	 */
	NETWORK_FIXED_IP: () => LocalizedString
	/**
	 * Brama
	 */
	NETWORK_GATEWAY: () => LocalizedString
	/**
	 * Maska podsieci
	 */
	NETWORK_SUBNET: () => LocalizedString
	/**
	 * Serwery DNS
	 */
	NETWORK_DNS: () => LocalizedString
	/**
	 * Adres {0}
	 */
	ADDRESS_OF: (arg0: unknown) => LocalizedString
	/**
	 * administratora
	 */
	ADMINISTRATOR: () => LocalizedString
	/**
	 * gościa
	 */
	GUEST: () => LocalizedString
	/**
	 * nowe{{go|j|}}
	 */
	NEW: (arg0: number | string | boolean) => LocalizedString
	/**
	 * Nowa nazwa {0}
	 */
	NEW_NAME_OF: (arg0: unknown) => LocalizedString
	/**
	 * encji
	 */
	ENTITY: () => LocalizedString
	/**
	 * Min.
	 */
	MIN: () => LocalizedString
	/**
	 * Maks.
	 */
	MAX: () => LocalizedString
	/**
	 * Niezapisane zmiany!
	 */
	BLOCK_NAVIGATE_1: () => LocalizedString
	/**
	 * Jeśli przejdziesz do innej strony, wprowadzone zmiany w ustawieniach zostaną utracone. Na pewno chcesz opuścić tę stronę?
	 */
	BLOCK_NAVIGATE_2: () => LocalizedString
	/**
	 * Pozostań
	 */
	STAY: () => LocalizedString
	/**
	 * Opuść
	 */
	LEAVE: () => LocalizedString
	/**
	 * Harmonogram
	 */
	SCHEDULER: () => LocalizedString
	/**
	 * Zautomatyzuj wykonywanie komend, dodając poniżej harmonogram zdarzeń. Nadaj mu unikalną nazwę, aby móc go aktywować/dezaktywować przez API/MQTT
	 */
	SCHEDULER_HELP_1: () => LocalizedString
	/**
	 * Wpisz 00:00 aby wykonywać jednorazowo przy starcie.
	 */
	SCHEDULER_HELP_2: () => LocalizedString
	/**
	 * {{H|h|}}armonogram{{u|}}
	 */
	SCHEDULE: (arg0: number | string | boolean) => LocalizedString
	/**
	 * {{Czas|Godzina|}}
	 */
	TIME: (arg0: number | string | boolean) => LocalizedString
	/**
	 * {{m|M|}}inutnik
	 */
	TIMER: (arg0: number | string | boolean) => LocalizedString
	/**
	 * O zmianie
	 */
	ONCHANGE: () => LocalizedString
	/**
	 * Stan
	 */
	CONDITION: () => LocalizedString
	/**
	 * Natychmiastowy
	 */
	IMMEDIATE: () => LocalizedString
	/**
	 * Harmonogram został uaktualniony.
	 */
	SCHEDULE_UPDATED: () => LocalizedString
	/**
	 * przy starcie
	 */
	SCHEDULE_TIMER_1: () => LocalizedString
	/**
	 * co minutę
	 */
	SCHEDULE_TIMER_2: () => LocalizedString
	/**
	 * co godzinę
	 */
	SCHEDULE_TIMER_3: () => LocalizedString
	/**
	 * {{N|n|}}iestandardowe{{j|}} encj{{e|i|}}
	 */
	CUSTOM_ENTITIES: (arg0: number | string | boolean) => LocalizedString
	/**
	 * Zdefiniuj niestandardowe encje dla magistrali EMS
	 */
	ENTITIES_HELP_1: () => LocalizedString
	/**
	 * Niestandardowe encje zostały uaktualnione.
	 */
	ENTITIES_UPDATED: () => LocalizedString
	/**
	 * Zapisywalna
	 */
	WRITEABLE: () => LocalizedString
	/**
	 * Wyświetlane
	 */
	SHOWING: () => LocalizedString
	/**
	 * Szukaj
	 */
	SEARCH: () => LocalizedString
	/**
	 * Certyfikat główny TLS (pozostaw puste dla TLS-insecure)
	 */
	CERT: () => LocalizedString
	/**
	 * Włącz wsparcie dla TLS
	 */
	ENABLE_TLS: () => LocalizedString
	/**
	 * włączony
	 */
	ON: () => LocalizedString
	/**
	 * wyłączony
	 */
	OFF: () => LocalizedString
	/**
	 * Typ przekaźnika
	 */
	POLARITY: () => LocalizedString
	/**
	 * Wyzwalany stanem wysokim
	 */
	ACTIVEHIGH: () => LocalizedString
	/**
	 * Wyzwalany stanem niskim
	 */
	ACTIVELOW: () => LocalizedString
	/**
	 * Zachowaj stan
	 */
	UNCHANGED: () => LocalizedString
	/**
	 * Zawsze
	 */
	ALWAYS: () => LocalizedString
	/**
	 * Aktywność
	 */
	ACTIVITY: () => LocalizedString
	/**
	 * Konfiguracja {0}
	 */
	CONFIGURE: (arg0: unknown) => LocalizedString
	/**
	 * Pamięć systemowa
	 */
	SYSTEM_MEMORY: () => LocalizedString
	/**
	 * Modyfikacja ustawień aplikacji EMS-ESP
	 */
	APPLICATION_SETTINGS_1: () => LocalizedString
	/**
	 * Dodawanie i usuwanie użytkowników
	 */
	SECURITY_1: () => LocalizedString
	/**
	 * Pobieranie/wysyłanie ustawień i firmware
	 */
	DOWNLOAD_UPLOAD_1: () => LocalizedString
	/**
	 * Moduł
	 */
	MODULES: () => LocalizedString
	/**
	 * Aktywuj lub dezaktywuj moduły zewnętrzne
	 */
	MODULES_1: () => LocalizedString
	/**
	 * Zaktualizowano moduły
	 */
	MODULES_UPDATED: () => LocalizedString
	/**
	 * Kliknij na moduł aby aktywować lub dezaktywować bibliotekę modułów EMS-ESP
	 */
	MODULES_DESCRIPTION: () => LocalizedString
	/**
	 * Brak wykrytych modułów zewnętrznych
	 */
	MODULES_NONE: () => LocalizedString
	/**
	 * Zmień nazwę
	 */
	RENAME: () => LocalizedString
	/**
	 * Aktywuj Modbus
	 */
	ENABLE_MODBUS: () => LocalizedString
	/**
	 * Zdiagnozuj problemy
	 */
	VIEW_LOG: () => LocalizedString
	/**
	 * przeciągnij i upuść plik lub kliknij tutaj
	 */
	UPLOAD_DRAG: () => LocalizedString
	/**
	 * Usługi
	 */
	SERVICES: () => LocalizedString
	/**
	 * Wszystkie wartości
	 */
	ALLVALUES: () => LocalizedString
	/**
	 * Specjalne funkcje
	 */
	SPECIAL_FUNCTIONS: () => LocalizedString
	/**
	 * Firmware ściąga się i instaluje
	 */
	WAIT_FIRMWARE: () => LocalizedString
	/**
	 * To zainstaluje wersję {1} {0}. Jesteś pewny?
	 */
	INSTALL_VERSION: (arg0: unknown, arg1: unknown) => LocalizedString
	/**
	 * aktualizacja dostępna
	 */
	UPDATE_AVAILABLE: () => LocalizedString
	/**
	 * Jesteś używając najnowszej wersji firmware {0}
	 */
	LATEST_VERSION: (arg0: unknown) => LocalizedString
	/**
	 * Proszę czekać
	 */
	PLEASE_WAIT: () => LocalizedString
	/**
	 * Uruchamianie
	 */
	RESTARTING_PRE: () => LocalizedString
	/**
	 * Przygotowanie
	 */
	RESTARTING_POST: () => LocalizedString
	/**
	 * Auto Scroll
	 */
	AUTO_SCROLL: () => LocalizedString
	/**
	 * Pulpit
	 */
	DASHBOARD: () => LocalizedString
	/**
	 * Tryb programisty
	 */
	DEVELOPER_MODE: () => LocalizedString
	/**
	 * Bajty
	 */
	BYTES: () => LocalizedString
	/**
	 * Bit Mask
	 */
	BITMASK: () => LocalizedString
	/**
	 * Duplicate
	 */
	DUPLICATE: () => LocalizedString
	/**
	 * All EMS entities that are active and marked as Favorite, plus all Custom Entities, Schedules and external Sensors data are displayed below.
	 */
	DASHBOARD_1: () => LocalizedString
	/**
	 * Brak ulubionych encji EMS. Użyj
	 */
	NO_DATA_1: () => LocalizedString
	/**
	 * moduł do ich oznaczenia.
	 */
	NO_DATA_2: () => LocalizedString
	/**
	 * Aby zobaczyć wszystkie dostępne encje przejdź do
	 */
	NO_DATA_3: () => LocalizedString
	/**
	 * Nie znaleziono dostępnych pinów GPIO
	 */
	NO_GPIO: () => LocalizedString
	/**
	 * Ta wersja
	 */
	THIS_VERSION: () => LocalizedString
	/**
	 * Platforma
	 */
	PLATFORM: () => LocalizedString
	/**
	 * Typ wydania
	 */
	RELEASE_TYPE: () => LocalizedString
	/**
	 * Połączenie internetowe jest wymagane do automatycznej kontroli wersji i aktualizacji
	 */
	INTERNET_CONNECTION_REQUIRED: () => LocalizedString
	/**
	 * Zmień na {0} wydanie
	 */
	SWITCH_RELEASE_TYPE: (arg0: unknown) => LocalizedString
	/**
	 * Informacje o wersji firmware
	 */
	FIRMWARE_VERSION_INFO: () => LocalizedString
	/**
	 * Brak danych
	 */
	NO_DATA: () => LocalizedString
	/**
	 * Profil użytkownika
	 */
	USER_PROFILE: () => LocalizedString
	/**
	 * Zapisane wersje
	 */
	STORED_VERSIONS: () => LocalizedString
	/**
	 * pomoc online
	 */
	ONLINE_HELP: () => LocalizedString
	/**
	 * Aktualizuj ważne wiadomości
	 */
	UPGRADE_IMPORTANT_MESSAGES: () => LocalizedString
	/**
	 * Ta aktualizacja wymaga resetu fabrycznego. Upewnij się, że najpierw pobierzesz kopię zapasową systemu przed kontynuowaniem, a następnie przesuń tę plik po zainstalowaniu nowej wersji.
	 */
	UPGRADE_IMPORTANT_MESSAGES_1: () => LocalizedString
	/**
	 * Aktualizujesz się do nowej głównej wersji. Upewnij się, że przeczytałeś ChangeLog dla wszelkich istotnych zmian.
	 */
	UPGRADE_IMPORTANT_MESSAGES_2: () => LocalizedString
	/**
	 * To spowoduje utworzenie kopii zapasowej całej konfiguracji i ustawień systemu. Wszystkie hasła będą widoczne w pliku kopii zapasowej. Bądź ostrożny przy udostępnianiu! Chcesz kontynuować?
	 */
	WARNING_SYSTEM_BACKUP: () => LocalizedString
}

export type Formatters = {}
