// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */

import { initFormatters } from './formatters'
import type { Locales, Translations } from './i18n-types'
import { loadedFormatters, loadedLocales, locales } from './i18n-util'

import cz from './cz'
import de from './de'
import en from './en'
import fr from './fr'
import it from './it'
import nl from './nl'
import no from './no'
import pl from './pl'
import sk from './sk'
import sv from './sv'
import tr from './tr'

const localeTranslations = {
	cz,
	de,
	en,
	fr,
	it,
	nl,
	no,
	pl,
	sk,
	sv,
	tr,
}

export const loadLocale = (locale: Locales): void => {
	if (loadedLocales[locale]) return

	loadedLocales[locale] = localeTranslations[locale] as unknown as Translations
	loadFormatters(locale)
}

export const loadAllLocales = (): void => locales.forEach(loadLocale)

export const loadFormatters = (locale: Locales): void =>
	void (loadedFormatters[locale] = initFormatters(locale))
